#!/bin/sh

while read local_ref local_sha remote_ref remote_sha
do
  if [ "$remote_ref" = "refs/heads/main" ]; then
    echo "Direct push to main is blocked."
    echo "Create a feature branch and open a Pull Request instead."
    exit 1
  fi
done

exit 0
