// Generated by scripts/contracts/generate-core-v1.cjs. Do not edit.
import { z } from 'zod';

export const CORE_V1_CONTRACT_VERSION = '1.0.0' as const;

export type AccountId = string;
export const AccountIdSchema: z.ZodType<AccountId> = z.string().uuid();

export type PlayerId = string;
export const PlayerIdSchema: z.ZodType<PlayerId> = z.string().uuid();

export type ProfileId = string;
export const ProfileIdSchema: z.ZodType<ProfileId> = z.string().uuid();

export type SessionId = string;
export const SessionIdSchema: z.ZodType<SessionId> = z.string().min(1).max(160);

export type RequestId = string;
export const RequestIdSchema: z.ZodType<RequestId> = z.string().min(8).max(160);

export type IdempotencyKey = string;
export const IdempotencyKeySchema: z.ZodType<IdempotencyKey> = z
  .string()
  .min(16)
  .max(128)
  .regex(new RegExp('^[A-Za-z0-9._:-]+$'));

export type PlayerLifecycleStateV1 =
  'registered' | 'onboarding' | 'active' | 'suspended' | 'deleting' | 'deleted';
export const PlayerLifecycleStateV1Schema: z.ZodType<PlayerLifecycleStateV1> =
  z.enum([
    'registered',
    'onboarding',
    'active',
    'suspended',
    'deleting',
    'deleted',
  ]);

export type AuthenticatedPrincipalV1 = {
  readonly accountId: AccountId;
  readonly playerId: PlayerId | null;
  readonly sessionId: SessionId;
  readonly issuedAt: string;
  readonly expiresAt: string;
};
export const AuthenticatedPrincipalV1Schema: z.ZodType<AuthenticatedPrincipalV1> =
  z
    .object({
      accountId: z.lazy(() => AccountIdSchema),
      playerId: z.union([z.lazy(() => PlayerIdSchema), z.null()]),
      sessionId: z.lazy(() => SessionIdSchema),
      issuedAt: z.string().datetime({ offset: true }),
      expiresAt: z.string().datetime({ offset: true }),
    })
    .strict();

export type PlayerLifecycleSnapshotV1 = {
  readonly playerId: PlayerId;
  readonly profileId: ProfileId;
  readonly state: PlayerLifecycleStateV1;
  readonly version: number;
  readonly discoverable: boolean;
  readonly messagingAllowed: boolean;
  readonly updatedAt: string;
};
export const PlayerLifecycleSnapshotV1Schema: z.ZodType<PlayerLifecycleSnapshotV1> =
  z
    .object({
      playerId: z.lazy(() => PlayerIdSchema),
      profileId: z.lazy(() => ProfileIdSchema),
      state: z.lazy(() => PlayerLifecycleStateV1Schema),
      version: z.number().int().min(0),
      discoverable: z.boolean(),
      messagingAllowed: z.boolean(),
      updatedAt: z.string().datetime({ offset: true }),
    })
    .strict();

export type MinimumActiveProfileV1 = {
  readonly displayName: string;
  readonly gameHandle: string;
  readonly rankId: string;
  readonly roleIds: readonly string[];
  readonly favoriteHeroIds: readonly string[];
  readonly timezone: string;
};
export const MinimumActiveProfileV1Schema: z.ZodType<MinimumActiveProfileV1> = z
  .object({
    displayName: z.string().min(2).max(40),
    gameHandle: z.string().min(2).max(64),
    rankId: z.string().min(1).max(80),
    roleIds: z
      .array(z.string().min(1).max(80))
      .min(1)
      .max(2)
      .refine(
        (items) => new Set(items).size === items.length,
        'Array items must be unique.',
      ),
    favoriteHeroIds: z
      .array(z.string().min(1).max(80))
      .min(3)
      .max(3)
      .refine(
        (items) => new Set(items).size === items.length,
        'Array items must be unique.',
      ),
    timezone: z.string().min(1).max(80),
  })
  .strict();

export type CompletePlayerOnboardingCommandV1 = {
  readonly idempotencyKey: IdempotencyKey;
  readonly expectedProfileVersion: number;
  readonly profile: MinimumActiveProfileV1;
};
export const CompletePlayerOnboardingCommandV1Schema: z.ZodType<CompletePlayerOnboardingCommandV1> =
  z
    .object({
      idempotencyKey: z.lazy(() => IdempotencyKeySchema),
      expectedProfileVersion: z.number().int().min(0),
      profile: z.lazy(() => MinimumActiveProfileV1Schema),
    })
    .strict();

export type CompletePlayerOnboardingResultV1 = {
  readonly principal: AuthenticatedPrincipalV1;
  readonly lifecycle: PlayerLifecycleSnapshotV1;
  readonly profileVersion: number;
  readonly replayed: boolean;
};
export const CompletePlayerOnboardingResultV1Schema: z.ZodType<CompletePlayerOnboardingResultV1> =
  z
    .object({
      principal: z.lazy(() => AuthenticatedPrincipalV1Schema),
      lifecycle: z.lazy(() => PlayerLifecycleSnapshotV1Schema),
      profileVersion: z.number().int().min(1),
      replayed: z.boolean(),
    })
    .strict();

export type CoreErrorCodeV1 =
  | 'authentication_required'
  | 'session_expired'
  | 'player_not_found'
  | 'player_suspended'
  | 'player_deleting'
  | 'player_deleted'
  | 'profile_incomplete'
  | 'profile_version_conflict'
  | 'invalid_lifecycle_transition'
  | 'idempotency_key_reused'
  | 'request_validation_failed';
export const CoreErrorCodeV1Schema: z.ZodType<CoreErrorCodeV1> = z.enum([
  'authentication_required',
  'session_expired',
  'player_not_found',
  'player_suspended',
  'player_deleting',
  'player_deleted',
  'profile_incomplete',
  'profile_version_conflict',
  'invalid_lifecycle_transition',
  'idempotency_key_reused',
  'request_validation_failed',
]);

export type CoreErrorV1 = {
  readonly code: CoreErrorCodeV1;
  readonly message: string;
  readonly requestId: RequestId;
  readonly retryable: boolean;
  readonly details?: { readonly [key: string]: unknown };
};
export const CoreErrorV1Schema: z.ZodType<CoreErrorV1> = z
  .object({
    code: z.lazy(() => CoreErrorCodeV1Schema),
    message: z.string().min(1).max(500),
    requestId: z.lazy(() => RequestIdSchema),
    retryable: z.boolean(),
    details: z.object({}).passthrough().optional(),
  })
  .strict();

export type PlayerLifecycleEventTypeV1 =
  | 'player.activated.v1'
  | 'player.profile_updated.v1'
  | 'player.suspended.v1'
  | 'player.deletion_requested.v1'
  | 'player.deleted.v1';
export const PlayerLifecycleEventTypeV1Schema: z.ZodType<PlayerLifecycleEventTypeV1> =
  z.enum([
    'player.activated.v1',
    'player.profile_updated.v1',
    'player.suspended.v1',
    'player.deletion_requested.v1',
    'player.deleted.v1',
  ]);

export type PlayerLifecycleEventV1 = {
  readonly eventId: string;
  readonly eventType: PlayerLifecycleEventTypeV1;
  readonly occurredAt: string;
  readonly accountId: AccountId;
  readonly playerId: PlayerId;
  readonly profileId: ProfileId;
  readonly lifecycleVersion: number;
  readonly profileVersion?: number;
  readonly reasonCode?: string;
};
export const PlayerLifecycleEventV1Schema: z.ZodType<PlayerLifecycleEventV1> = z
  .object({
    eventId: z.string().uuid(),
    eventType: z.lazy(() => PlayerLifecycleEventTypeV1Schema),
    occurredAt: z.string().datetime({ offset: true }),
    accountId: z.lazy(() => AccountIdSchema),
    playerId: z.lazy(() => PlayerIdSchema),
    profileId: z.lazy(() => ProfileIdSchema),
    lifecycleVersion: z.number().int().min(1),
    profileVersion: z.number().int().min(0).optional(),
    reasonCode: z.string().min(1).max(120).optional(),
  })
  .strict();

export const coreV1ProviderFixtures = {
  'authenticatedPrincipal.valid': {
    schema: 'AuthenticatedPrincipalV1',
    value: {
      accountId: '00000000-0000-4000-8000-000000000101',
      playerId: '10000000-0000-4000-8000-000000000101',
      sessionId: 'session-00000000-0000-4000-8000-000000000101',
      issuedAt: '2026-07-14T00:00:00.000Z',
      expiresAt: '2026-07-14T01:00:00.000Z',
    },
  },
  'authenticatedPrincipal.expired': {
    schema: 'AuthenticatedPrincipalV1',
    value: {
      accountId: '00000000-0000-4000-8000-000000000102',
      playerId: '10000000-0000-4000-8000-000000000102',
      sessionId: 'session-expired-00000000-0000-4000-8000-000000000102',
      issuedAt: '2026-07-13T00:00:00.000Z',
      expiresAt: '2026-07-13T01:00:00.000Z',
    },
  },
  'lifecycle.onboarding': {
    schema: 'PlayerLifecycleSnapshotV1',
    value: {
      playerId: '10000000-0000-4000-8000-000000000103',
      profileId: '20000000-0000-4000-8000-000000000103',
      state: 'onboarding',
      version: 1,
      discoverable: false,
      messagingAllowed: false,
      updatedAt: '2026-07-14T00:05:00.000Z',
    },
  },
  'lifecycle.active': {
    schema: 'PlayerLifecycleSnapshotV1',
    value: {
      playerId: '10000000-0000-4000-8000-000000000104',
      profileId: '20000000-0000-4000-8000-000000000104',
      state: 'active',
      version: 2,
      discoverable: true,
      messagingAllowed: true,
      updatedAt: '2026-07-14T00:10:00.000Z',
    },
  },
  'lifecycle.suspended': {
    schema: 'PlayerLifecycleSnapshotV1',
    value: {
      playerId: '10000000-0000-4000-8000-000000000105',
      profileId: '20000000-0000-4000-8000-000000000105',
      state: 'suspended',
      version: 3,
      discoverable: false,
      messagingAllowed: false,
      updatedAt: '2026-07-14T00:15:00.000Z',
    },
  },
  'lifecycle.deleting': {
    schema: 'PlayerLifecycleSnapshotV1',
    value: {
      playerId: '10000000-0000-4000-8000-000000000106',
      profileId: '20000000-0000-4000-8000-000000000106',
      state: 'deleting',
      version: 4,
      discoverable: false,
      messagingAllowed: false,
      updatedAt: '2026-07-14T00:20:00.000Z',
    },
  },
  'error.profileVersionConflict': {
    schema: 'CoreErrorV1',
    value: {
      code: 'profile_version_conflict',
      message: 'Profile changed on another session.',
      requestId: 'request-profile-conflict-0001',
      retryable: true,
      details: {
        expectedVersion: 2,
        actualVersion: 3,
      },
    },
  },
  'completion.idempotentReplay': {
    schema: 'CompletePlayerOnboardingResultV1',
    value: {
      principal: {
        accountId: '00000000-0000-4000-8000-000000000107',
        playerId: '10000000-0000-4000-8000-000000000107',
        sessionId: 'session-00000000-0000-4000-8000-000000000107',
        issuedAt: '2026-07-14T00:00:00.000Z',
        expiresAt: '2026-07-14T01:00:00.000Z',
      },
      lifecycle: {
        playerId: '10000000-0000-4000-8000-000000000107',
        profileId: '20000000-0000-4000-8000-000000000107',
        state: 'active',
        version: 2,
        discoverable: true,
        messagingAllowed: true,
        updatedAt: '2026-07-14T00:30:00.000Z',
      },
      profileVersion: 1,
      replayed: true,
    },
  },
} as const;

export const coreV1ConsumerFixtures = {
  'mission2.discoveryEligibility': [
    'lifecycle.onboarding',
    'lifecycle.active',
    'lifecycle.suspended',
    'lifecycle.deleting',
  ],
  'mission3.messagingAuthorization': [
    'authenticatedPrincipal.valid',
    'lifecycle.active',
    'lifecycle.suspended',
    'lifecycle.deleting',
  ],
  'mission4.sessionAndDeepLinks': [
    'authenticatedPrincipal.valid',
    'authenticatedPrincipal.expired',
    'lifecycle.onboarding',
    'lifecycle.deleting',
  ],
} as const;

export function parseCoreV1Fixture(name: keyof typeof coreV1ProviderFixtures) {
  const fixture = coreV1ProviderFixtures[name];
  const schema = coreV1Schemas[fixture.schema];
  return schema.parse(fixture.value);
}

export const coreV1Schemas = {
  AccountId: AccountIdSchema,
  PlayerId: PlayerIdSchema,
  ProfileId: ProfileIdSchema,
  SessionId: SessionIdSchema,
  RequestId: RequestIdSchema,
  IdempotencyKey: IdempotencyKeySchema,
  PlayerLifecycleStateV1: PlayerLifecycleStateV1Schema,
  AuthenticatedPrincipalV1: AuthenticatedPrincipalV1Schema,
  PlayerLifecycleSnapshotV1: PlayerLifecycleSnapshotV1Schema,
  MinimumActiveProfileV1: MinimumActiveProfileV1Schema,
  CompletePlayerOnboardingCommandV1: CompletePlayerOnboardingCommandV1Schema,
  CompletePlayerOnboardingResultV1: CompletePlayerOnboardingResultV1Schema,
  CoreErrorCodeV1: CoreErrorCodeV1Schema,
  CoreErrorV1: CoreErrorV1Schema,
  PlayerLifecycleEventTypeV1: PlayerLifecycleEventTypeV1Schema,
  PlayerLifecycleEventV1: PlayerLifecycleEventV1Schema,
} as const;
