import { StyleSheet } from 'react-native';

import {
  liquidColors,
  liquidTypography,
} from '@/shared/theme/liquid-glass.tokens';

export const homeDashboardStyles = StyleSheet.create({
  currentSessionActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 12,
  },
  currentSessionCard: { padding: 16 },
  currentSessionCardHost: { marginBottom: 16 },
  currentSessionCopy: { flex: 1 },
  currentSessionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  currentSessionMeta: { ...liquidTypography.body, marginTop: 5 },
  currentSessionTitle: { ...liquidTypography.cardTitle, marginTop: 4 },
  queryStateDescription: {
    color: 'rgba(224,230,248,0.72)',
    fontSize: 14,
    lineHeight: 21,
    maxWidth: 320,
    textAlign: 'center',
  },
  queryStateScreen: {
    alignItems: 'center',
    flexGrow: 1,
    gap: 14,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  queryStateTitle: {
    color: '#F7F8FF',
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
  },
  bgCyanGlow: {
    backgroundColor: 'rgba(60,210,255,0.016)',
    borderRadius: 300,
    height: 560,
    position: 'absolute',
    right: -342,
    top: 154,
    width: 560,
  },
  bgPurpleGlow: {
    backgroundColor: 'rgba(130,80,255,0.020)',
    borderRadius: 300,
    height: 560,
    left: -360,
    position: 'absolute',
    top: -104,
    width: 560,
  },
  bgVignette: {
    backgroundColor: 'rgba(0,0,0,0.10)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  cardActionDepthShadow: {
    backgroundColor: 'rgba(0,0,0,0.12)',
    borderRadius: 22,
    bottom: -7,
    left: 4,
    position: 'absolute',
    right: 4,
    top: 7,
    zIndex: 0,
  },
  matchCardDarkTint: {
    backgroundColor: 'rgba(3,6,18,0.24)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  matchCardDepthShadow: {
    backgroundColor: 'rgba(0,0,0,0.20)',
    borderRadius: 29,
    bottom: -18,
    left: 14,
    position: 'absolute',
    right: 14,
    top: 16,
    zIndex: 0,
  },
  primaryActionDepthShadow: {
    backgroundColor: 'rgba(0,0,0,0.14)',
    borderRadius: 28,
    bottom: -8,
    left: 8,
    position: 'absolute',
    right: 8,
    top: 9,
    zIndex: 0,
  },
  readyBoardDarkTint: {
    backgroundColor: 'rgba(3,6,18,0.06)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  readyBoardDepthShadow: {
    backgroundColor: 'rgba(0,0,0,0.20)',
    borderRadius: 32,
    bottom: -20,
    left: 22,
    position: 'absolute',
    right: 22,
    top: 22,
    zIndex: 0,
  },
  ambientGlow: {
    borderRadius: 999,
    position: 'absolute',
  },
  ambientGlowLeft: {
    backgroundColor: 'rgba(129,76,255,0.14)',
    height: 220,
    left: -126,
    top: 28,
    width: 220,
  },
  ambientGlowRight: {
    backgroundColor: 'rgba(54,168,255,0.10)',
    height: 260,
    right: -152,
    top: 176,
    width: 260,
  },
  avatarPressed: { opacity: 0.86, transform: [{ scale: 0.975 }] },
  avatarFallback: {
    alignItems: 'center',
    backgroundColor: 'rgba(6,8,18,0.95)',
    justifyContent: 'center',
  },
  avatarInitials: { color: '#F7F8FF', fontSize: 16, fontWeight: '900' },
  avatarRing: {
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#B073FF',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.36,
    shadowRadius: 13,
  },
  avatarStatusBadge: {
    borderColor: '#06101E',
    borderRadius: 99,
    borderWidth: 3,
    bottom: 4,
    height: 14,
    left: 4,
    position: 'absolute',
    width: 14,
  },
  boardHeaderRow: { minHeight: 42, position: 'relative' },
  boardSubtitle: {
    color: '#D1D7E8',
    fontSize: 11,
    fontWeight: '500',
    letterSpacing: -0.04,
    lineHeight: 15,
    marginTop: 1,
    maxWidth: 246,
  },
  boardTitle: {
    ...liquidTypography.heroTitle,
    fontWeight: '700',
    letterSpacing: -0.24,
    lineHeight: 23,
    marginTop: 3,
    textShadowColor: 'rgba(255,255,255,0.10)',
    textShadowOffset: { height: 0, width: 0 },
    textShadowRadius: 3,
  },
  boardTitleBlock: { minWidth: 0, paddingRight: 0 },
  bottomFade: {
    backgroundColor: 'rgba(1,3,8,0.46)',
    bottom: 0,
    height: 150,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  actionIconForeground: { zIndex: 2 },
  chatUnreadBadge: {
    borderRadius: 8,
    height: 16,
    minWidth: 16,
    paddingHorizontal: 0,
  },
  chatUnreadBadgeHost: { right: -2, top: -2 },
  cardActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginLeft: 4,
  },
  cardHalo: {
    borderRadius: 27,
    borderWidth: 1,
    bottom: 0,
    left: 0,
    opacity: 0.24,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  cardPrimaryActionEdgeLine: {
    borderRadius: 999,
    height: 1,
    left: 14,
    opacity: 0.22,
    position: 'absolute',
    right: 16,
    top: 1,
  },
  cardPrimaryActionSheen: {
    borderRadius: 21,
    bottom: 0,
    left: -12,
    opacity: 0.2,
    position: 'absolute',
    right: -12,
    top: -8,
  },
  cardPrimaryAction: {
    borderRadius: 19,
    elevation: 2,
    minWidth: 68,
    overflow: 'visible',
    position: 'relative',
    shadowColor: '#C679FF',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
  },
  cardPrimaryActionGradient: {
    alignItems: 'center',
    borderColor: 'rgba(255,255,255,0.10)',
    borderRadius: 19,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 30,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
    zIndex: 2,
  },
  cardPrimaryActionText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: -0.08,
    zIndex: 2,
  },
  cardStatusDot: {
    borderRadius: 99,
    height: 8,
    marginRight: 5,
    width: 8,
  },
  emptyBody: {
    color: '#A8AFC6',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 18,
    marginTop: 7,
    textAlign: 'center',
  },
  emptyCard: {
    alignItems: 'stretch',
    backgroundColor: 'rgba(6,11,25,0.78)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 30,
    borderWidth: 1,
    overflow: 'hidden',
    padding: 18,
  },
  emptyCardShell: { marginTop: 17 },
  emptyIcon: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(198,121,255,0.14)',
    borderRadius: 999,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  emptyPreviewAvatar: {
    backgroundColor: 'rgba(198,121,255,0.45)',
    borderRadius: 999,
    height: 34,
    width: 34,
  },
  emptyPreviewLine: {
    backgroundColor: 'rgba(255,255,255,0.13)',
    borderRadius: 999,
    height: 8,
  },
  emptyPreviewLineLong: { width: '78%' },
  emptyPreviewLineShort: { width: '46%' },
  emptyPreviewLines: { flex: 1, gap: 7 },
  emptyPreviewPill: {
    backgroundColor: '#F7F8FF',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  emptyPreviewPillText: {
    color: '#10131F',
    fontSize: 11,
    fontWeight: '900',
  },
  emptyPreviewRow: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
    padding: 10,
  },
  emptyTitle: {
    color: '#F7F8FF',
    fontSize: 16,
    fontWeight: '900',
    marginTop: 12,
    textAlign: 'center',
  },
  eyebrow: {
    color: '#B179FF',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.22,
  },
  footerSeparator: {
    color: 'rgba(226,232,255,0.52)',
    fontSize: 10,
    fontWeight: '700',
    marginHorizontal: 5,
  },
  greeting: {
    ...liquidTypography.screenGreeting,
    fontSize: 13,
    fontWeight: '500',
  },
  greetingBlock: { flex: 1, minWidth: 0 },
  identityRow: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 10,
    minWidth: 0,
  },
  kindPill: {
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    flexShrink: 0,
    gap: 5,
    maxWidth: 124,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  kindPillSheen: {
    borderRadius: 18,
    bottom: 0,
    left: 0,
    opacity: 0.78,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  kindText: { fontSize: 9, fontWeight: '700', zIndex: 2 },
  liveBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 8,
    paddingVertical: 5,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  liveDot: {
    backgroundColor: '#AEB7D0',
    borderRadius: 99,
    height: 7,
    width: 7,
  },
  liveDotActive: { backgroundColor: '#5DFFB3' },
  liveText: { color: '#DDE6FF', fontSize: 10, fontWeight: '600' },
  matchAvatarWrap: { position: 'relative' },
  matchCardPressable: {
    borderRadius: 30,
    position: 'relative',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.07,
    shadowRadius: 13,
  },
  matchCard: {
    backgroundColor: 'rgba(9,11,24,0.58)',
    borderRadius: 27,
    minHeight: 102,
    overflow: 'hidden',
    paddingBottom: 8,
    paddingHorizontal: 8,
    paddingTop: 8,
  },
  matchCardFrame: {
    borderRadius: 28,
    overflow: 'visible',
    position: 'relative',
    shadowColor: '#000000',
    shadowOffset: { height: 12, width: 0 },
    elevation: 7,
    shadowOpacity: 0.2,
    shadowRadius: 26,
  },
  matchCardSheen: {
    height: 46,
    left: 0,
    opacity: 0.06,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  matchCardInnerReflection: {
    bottom: 0,
    left: 0,
    opacity: 0.08,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  matchEdgeSpark: {
    borderRadius: 999,
    opacity: 0.3,
    position: 'absolute',
  },
  matchEdgeSparkBottom: {
    bottom: 0,
    height: 1,
    opacity: 0.18,
    right: 30,
    width: 126,
  },
  matchEdgeSparkRight: {
    bottom: 24,
    opacity: 0.24,
    right: 0,
    top: 24,
    width: 1,
  },
  matchEdgeSparkTop: {
    height: 1,
    left: 28,
    opacity: 0.26,
    right: 70,
    top: 0,
  },
  matchCardTop: { alignItems: 'flex-start', flexDirection: 'row', gap: 8 },
  matchFooter: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
    marginTop: 4,
  },
  matchList: { gap: 8, marginTop: 9 },
  matchesSectionHeader: { marginTop: 9 },
  matchMainInfo: { flex: 1, minWidth: 0, paddingTop: 1 },
  matchMeta: {
    color: 'rgba(214,220,237,0.90)',
    flex: 1,
    flexShrink: 1,
    fontSize: 9,
    fontWeight: '600',
    letterSpacing: -0.03,
    lineHeight: 13,
  },
  matchMetaBlock: { flex: 1, minWidth: 0 },
  matchName: {
    color: 'rgba(248,250,255,0.93)',
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: -0.2,
    lineHeight: 17,
  },
  matchNameRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    minHeight: 26,
  },
  matchSubtitle: {
    color: 'rgba(226,232,255,0.72)',
    fontSize: 10,
    fontWeight: '500',
    letterSpacing: -0.03,
    lineHeight: 14,
    marginTop: 1,
  },
  matchTagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginTop: 4,
    minWidth: 0,
  },
  miniStatusPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.13)',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    marginTop: 3,
    maxWidth: '100%',
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  miniStatusText: { color: '#F0F3FF', fontSize: 11, fontWeight: '600' },
  modeChip: {
    alignItems: 'center',
    borderRadius: 15,
    flex: 1,
    flexDirection: 'row',
    gap: 3,
    justifyContent: 'center',
    minHeight: 27,
    minWidth: 0,
    paddingHorizontal: 2,
    shadowColor: '#B073FF',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
  },
  modeChipSelected: {
    backgroundColor: 'rgba(126,69,255,0.20)',
    borderColor: 'rgba(220,174,255,0.24)',
    shadowOpacity: 0.05,
    shadowRadius: 6,
  },
  modeChipFrame: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.19)',
    borderRadius: 20,
    borderWidth: 1,
    overflow: 'hidden',
  },
  modeChipFrameSelected: {
    borderColor: 'rgba(220,174,255,0.86)',
    shadowColor: '#B073FF',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.58,
    shadowRadius: 13,
  },
  modeGrid: {
    flexDirection: 'row',
    gap: 4,
    marginTop: 5,
  },
  modeLabel: {
    color: '#CBD3E7',
    fontSize: 9.5,
    fontWeight: '600',
    letterSpacing: -0.08,
  },
  modeLabelSelected: { color: 'rgba(255,255,255,0.90)', fontWeight: '700' },
  notificationButton: {
    alignItems: 'center',
    borderRadius: 21,
    height: 42,
    justifyContent: 'center',
    marginLeft: 8,
    overflow: 'visible',
    shadowColor: '#FFFFFF',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    width: 42,
  },
  notificationDot: {
    backgroundColor: '#FF4F95',
    borderRadius: 99,
    height: 10,
    width: 10,
  },
  previewBanner: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,184,107,0.12)',
    borderColor: 'rgba(255,184,107,0.25)',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    marginTop: 18,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  previewText: { color: '#FFD9A8', flex: 1, fontSize: 12, fontWeight: '700' },
  pressed: { opacity: 0.82, transform: [{ scale: 0.985 }] },
  primaryAction: {
    borderRadius: 22,
    elevation: 2,
    minWidth: 114,
    overflow: 'visible',
    position: 'relative',
    shadowColor: '#9E77FF',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
  },
  primaryActionActive: {},
  primaryActionEdgeLine: {
    backgroundColor: 'rgba(255,255,255,0.46)',
    borderRadius: 999,
    height: 1,
    left: 18,
    opacity: 0.48,
    position: 'absolute',
    right: 18,
    top: 1,
  },
  primaryActionSheen: {
    borderRadius: 28,
    bottom: 0,
    left: -18,
    opacity: 0.18,
    position: 'absolute',
    right: -18,
    top: -10,
  },
  primaryActionGradient: {
    alignItems: 'center',
    borderColor: 'rgba(255,255,255,0.15)',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    minHeight: 32,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 6,
    zIndex: 2,
  },
  primaryActionText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: -0.04,
    zIndex: 2,
  },
  readyActionRow: {
    alignItems: 'center',
    borderTopColor: 'rgba(255,255,255,0.05)',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 6,
    marginTop: 5,
    paddingTop: 5,
  },
  readyBoardContent: {
    minHeight: 166,
    padding: 12,
    position: 'relative',
  },
  readyBoardSurface: {
    backgroundColor: 'rgba(7,10,23,0.52)',
    borderRadius: 27,
    minHeight: 166,
    overflow: 'hidden',
    padding: 0,
    zIndex: 2,
  },
  readyBoardBorder: {
    borderRadius: 28,
    elevation: 7,
    marginTop: 10,
    overflow: 'visible',
    position: 'relative',
    shadowColor: '#000000',
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
  },
  readyBoardEdgeSweep: {
    backgroundColor: 'rgba(100,230,255,0.23)',
    borderRadius: 999,
    bottom: 20,
    opacity: 0.08,
    position: 'absolute',
    right: 0,
    top: 32,
    width: 1,
  },
  readyBoardSheen: {
    height: 96,
    left: -20,
    position: 'absolute',
    right: -20,
    top: -22,
  },
  readyBoardInnerReflection: {
    bottom: 0,
    left: 0,
    opacity: 0.17,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  readyCopy: {
    color: '#F7F8FF',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: -0.03,
    lineHeight: 15,
  },
  readyCopyBlock: { flex: 1, minWidth: 0 },
  readyDescription: {
    color: '#C4CBDE',
    fontSize: 9,
    fontWeight: '500',
    lineHeight: 12,
    marginTop: 1,
  },
  readinessError: {
    color: 'rgba(255,190,199,0.88)',
    fontSize: 10,
    fontWeight: '600',
    lineHeight: 14,
    marginTop: 7,
  },
  readyHeroImage: {
    height: '100%',
    left: 0,
    opacity: 0.72,
    position: 'absolute',
    top: 0,
    transform: [{ scale: 1.18 }, { translateX: -18 }],
    width: '100%',
  },
  root: { backgroundColor: liquidColors.background.base, flex: 1 },
  safe: { flex: 1 },
  scrollContent: {
    paddingHorizontal: 18,
    paddingTop: 4,
  },
  secondaryAction: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderRadius: 16,
    height: 31,
    justifyContent: 'center',
    overflow: 'visible',
    position: 'relative',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 5,
    width: 31,
  },
  secondaryActionIcon: { zIndex: 3 },
  secondaryActionSurface: {
    backgroundColor: 'rgba(18,20,38,0.58)',
    borderRadius: 21,
    bottom: 0,
    left: 0,
    overflow: 'hidden',
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 2,
  },
  sectionEyebrow: {
    ...liquidTypography.sectionLabel,
    fontWeight: '700',
    letterSpacing: 0.38,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
    paddingHorizontal: 4,
  },
  sectionTitle: {
    ...liquidTypography.sectionTitle,
    color: 'rgba(248,250,255,0.92)',
    fontWeight: '600',
    letterSpacing: -0.22,
    marginTop: 5,
  },
  softTag: { flexShrink: 0 },
  softTagText: { fontSize: 9, fontWeight: '600', letterSpacing: -0.02 },
  statusLabel: { fontSize: 9, fontWeight: '700', maxWidth: 62 },
  statusMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    minWidth: 0,
  },
  surfaceFill: { bottom: 0, left: 0, position: 'absolute', right: 0, top: 0 },
  tabItem: {
    alignItems: 'center',
    borderRadius: 21,
    flex: 1,
    gap: 2,
    justifyContent: 'center',
    minHeight: 35,
    overflow: 'hidden',
    paddingVertical: 4,
  },
  tabItemActive: {
    borderColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    shadowColor: '#8C7BFF',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
  },
  tabLabel: { color: 'rgba(210,218,245,0.56)', fontSize: 8, fontWeight: '600' },
  tabLabelActive: { color: 'rgba(255,255,255,0.82)', fontWeight: '700' },
  tabsShell: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(15,18,32,0.24)',
    borderColor: 'rgba(255,255,255,0.065)',
    borderRadius: 24,
    borderWidth: 1,
    bottom: 16,
    flexDirection: 'row',
    gap: 4,
    left: 46,
    overflow: 'hidden',
    padding: 3,
    position: 'absolute',
    right: 46,
  },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 0,
  },
  userName: {
    ...liquidTypography.screenName,
    fontSize: 23,
    fontWeight: '700',
    letterSpacing: -0.3,
    lineHeight: 27,
    marginTop: 0,
  },
});
