import { StyleSheet } from 'react-native';

import {
  appColors,
  appMotion,
  appOpacity,
  appShadows,
  appSpacing,
  appTypography,
} from '@/shared/ui';
import { homeUi } from '../ui/home-ui';

export const homeDashboardStyles = StyleSheet.create({
  autoMatchRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  autoMatchText: {
    color: homeUi.colors.autoMatch,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.1,
  },
  chooseModeRow: {
    alignItems: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 2,
    marginTop: 10,
  },
  chooseModeText: {
    color: homeUi.colors.chooseMode,
    fontSize: 12,
    fontWeight: '700',
  },
  contextCard: {
    borderColor: homeUi.colors.contextStroke,
    borderRadius: homeUi.metrics.contextCard.radius,
    borderWidth: StyleSheet.hairlineWidth,
    flex: 1,
    height: homeUi.metrics.contextCard.height,
    minWidth: 0,
    overflow: 'hidden',
    shadowColor: homeUi.colors.cardShadow,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
  },
  contextCardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingTop: 12,
  },
  contextCardImage: {
    flex: 1,
  },
  contextCardImageRadius: {
    borderRadius: homeUi.metrics.contextCard.radius,
  },
  contextCardPressed: {
    opacity: 0.88,
    transform: [{ scale: appMotion.subtlePressScale }],
  },
  contextCardTitle: {
    color: homeUi.colors.cardTitle,
    flex: 1,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  contextGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  heroContent: {
    height: '100%',
    justifyContent: 'flex-start',
    paddingBottom: 14,
    paddingLeft: 16,
    paddingTop: 17,
    width: homeUi.metrics.hero.contentWidth,
  },
  heroCta: {
    alignItems: 'center',
    borderColor: homeUi.colors.ctaBorder,
    borderRadius: homeUi.metrics.hero.radius,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 8,
    height: 48,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  heroCtaPressable: {
    borderRadius: homeUi.metrics.hero.radius,
    marginTop: 15,
    shadowColor: homeUi.colors.ctaShadow,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.42,
    shadowRadius: 14,
    width: '100%',
  },
  heroCtaPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.98 }],
  },
  heroCtaText: {
    color: appColors.text.onAccent,
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: -0.15,
  },
  heroDescription: {
    color: homeUi.colors.heroDescription,
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 22,
    marginTop: 10,
  },
  heroImage: {
    height: '100%',
    width: '100%',
  },
  heroImageRadius: {
    borderRadius: homeUi.metrics.hero.radius,
  },
  heroShell: {
    borderColor: appColors.border.image,
    borderRadius: homeUi.metrics.hero.radius,
    borderWidth: StyleSheet.hairlineWidth,
    height: homeUi.metrics.hero.height,
    overflow: 'hidden',
    shadowColor: homeUi.colors.heroShadow,
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 24,
  },
  heroTitle: {
    ...appTypography.displayHero,
    color: appColors.text.onAccent,
    flexShrink: 1,
  },
  heroTitleIcon: {
    marginLeft: 4,
    marginTop: 1,
    textShadowColor: homeUi.colors.heroIconGlow,
    textShadowOffset: { height: 0, width: 0 },
    textShadowRadius: 12,
  },
  heroTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 9,
    minHeight: 39,
    width: 224,
  },
  miniAvatar: {
    borderColor: homeUi.colors.subtleWhiteBorder,
    borderRadius: 11,
    borderWidth: 1.5,
    height: 22,
    position: 'absolute',
    top: 0,
    width: 22,
  },
  miniAvatarStack: {
    height: 22,
    width: 58,
  },
  modeCard: {
    alignItems: 'center',
    backgroundColor: homeUi.colors.modeBackground,
    borderColor: appColors.border.control,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    flex: 1,
    gap: 5,
    height: homeUi.metrics.mode.cardHeight,
    justifyContent: 'center',
    minWidth: 0,
    paddingHorizontal: 2,
  },
  modeCardPressed: {
    opacity: 0.84,
    transform: [{ scale: 0.97 }],
  },
  modeCardSelected: {
    backgroundColor: homeUi.colors.selectedModeBackground,
    borderColor: appColors.border.focus,
    borderWidth: 1.5,
    shadowColor: appShadows.purpleGlow.shadowColor,
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.58,
    shadowRadius: 12,
  },
  modeGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  modeIconBubble: {
    alignItems: 'center',
    borderRadius: 18,
    height: homeUi.metrics.mode.icon,
    justifyContent: 'center',
    opacity: 0.92,
    width: homeUi.metrics.mode.icon,
  },
  modeIconBubbleSelected: {
    shadowColor: homeUi.colors.modeSelectedGlow,
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.7,
    shadowRadius: 10,
  },
  modeLabel: {
    color: homeUi.colors.modeLabel,
    fontSize: 11,
    fontWeight: '600',
  },
  modeLabelSelected: {
    color: appColors.text.onAccent,
    fontWeight: '800',
  },
  pressed: {
    opacity: appOpacity.pressed,
  },
  previewBanner: {
    alignItems: 'center',
    backgroundColor: homeUi.colors.previewBackground,
    borderColor: homeUi.colors.previewBorder,
    borderRadius: 13,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  previewText: {
    color: homeUi.colors.previewText,
    flex: 1,
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 16,
  },
  profileAvatarRing: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 2,
  },
  queryStateDescription: {
    color: homeUi.colors.queryText,
    fontSize: 14,
    lineHeight: 21,
    maxWidth: 290,
    textAlign: 'center',
  },
  queryStateScreen: {
    alignItems: 'center',
    flexGrow: 1,
    gap: appSpacing['2xl'],
    justifyContent: 'center',
    paddingBottom: 48,
  },
  queryStateTitle: {
    color: appColors.text.onAccent,
    fontSize: 21,
    fontWeight: '800',
    marginTop: 4,
    textAlign: 'center',
  },
  readinessError: {
    color: appColors.status.danger,
    fontSize: 11,
    lineHeight: 16,
    marginTop: -8,
    paddingHorizontal: 4,
  },
  recentGrid: {
    flexDirection: 'row',
    gap: 7,
  },
  recentHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  recentSection: {
    gap: 11,
  },
  recentTitle: {
    color: appColors.text.onAccent,
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  roomAvatar: {
    borderColor: homeUi.colors.roomAvatarBorder,
    borderRadius: 29,
    borderWidth: 2,
    height: 58,
    width: 58,
  },
  roomAvatarLeft: {
    zIndex: 1,
  },
  roomAvatarRight: {
    marginLeft: -10,
  },
  roomAvatars: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 19,
    position: 'relative',
  },
  roomCopy: {
    alignItems: 'center',
    bottom: 10,
    left: 8,
    position: 'absolute',
    right: 8,
  },
  roomDescription: {
    color: homeUi.colors.contextDescription,
    fontSize: 10,
    fontWeight: '500',
    lineHeight: 15,
    marginTop: 5,
    textAlign: 'center',
  },
  roomHeart: {
    alignItems: 'center',
    borderRadius: 16,
    bottom: -7,
    height: 32,
    justifyContent: 'center',
    left: '50%',
    marginLeft: -16,
    position: 'absolute',
    width: 32,
    zIndex: 3,
  },
  roomTitle: {
    color: appColors.text.onAccent,
    fontSize: 13,
    fontWeight: '800',
  },
  roomTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  scrollContent: {
    gap: appSpacing['3xl'],
    paddingBottom: appSpacing['6xl'],
    paddingHorizontal: appSpacing['2xl'],
    paddingTop: 9,
  },
  searchingAvatar: {
    borderRadius: 16,
    height: 30,
    width: 30,
  },
  searchingAvatarFrame: {
    backgroundColor: homeUi.colors.avatarFrame,
    borderColor: homeUi.colors.searchAvatarBorder,
    borderRadius: 17,
    borderWidth: 1.5,
    height: 33,
    padding: 1,
    position: 'absolute',
    top: 0,
    width: 33,
  },
  searchingAvatars: {
    height: 33,
    position: 'relative',
    width: 77,
  },
  searchingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 13,
  },
  searchingText: {
    color: homeUi.colors.searchingText,
    fontSize: 11,
    fontWeight: '500',
    lineHeight: 15,
  },
  sessionCta: {
    alignItems: 'center',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 7,
    height: 38,
    justifyContent: 'center',
  },
  sessionCtaPressable: {
    borderRadius: 18,
    bottom: 10,
    left: 11,
    position: 'absolute',
    right: 11,
    shadowColor: homeUi.colors.sessionCtaShadow,
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.34,
    shadowRadius: 10,
  },
  sessionCtaText: {
    color: appColors.text.onAccent,
    fontSize: 14,
    fontWeight: '800',
  },
  sessionDay: {
    color: homeUi.colors.sessionDay,
    fontSize: 9,
    fontWeight: '500',
    marginTop: 1,
  },
  sessionMeta: {
    color: homeUi.colors.sessionMeta,
    fontSize: 9,
    fontWeight: '500',
    marginTop: 2,
  },
  sessionMode: {
    color: homeUi.colors.sessionMode,
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '800',
  },
  sessionModeBlock: {
    flex: 1,
    minWidth: 0,
    paddingTop: 4,
  },
  sessionModeRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  sessionReadyCount: {
    color: appColors.text.onAccent,
    fontSize: 9.5,
    fontWeight: '800',
    marginLeft: 4,
  },
  sessionReadyLabel: {
    color: appColors.status.success,
    fontSize: 9.5,
    fontWeight: '800',
  },
  sessionReadyRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 10,
    paddingHorizontal: 11,
  },
  sessionSummaryRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
    paddingHorizontal: 11,
  },
  sessionTime: {
    color: appColors.text.onAccent,
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  sessionTimeBox: {
    alignItems: 'center',
    backgroundColor: homeUi.colors.sessionTimeBox,
    borderRadius: 10,
    minWidth: 48,
    paddingHorizontal: 5,
    paddingVertical: 7,
  },
  viewAllButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 1,
  },
  viewAllText: {
    color: homeUi.colors.viewAll,
    fontSize: 12,
    fontWeight: '600',
  },

  autoMatchTextCompact: {
    fontSize: 12,
  },
  chooseModeRowCompact: {
    marginTop: 6,
  },
  contextCardCompact: {
    borderRadius: homeUi.metrics.contextCard.radiusCompact,
    height: homeUi.metrics.contextCard.heightCompact,
  },
  contextCardImageRadiusCompact: {
    borderRadius: 18,
  },
  contextCardHeaderCompact: {
    paddingHorizontal: 10,
    paddingTop: 10,
  },
  contextCardTitleCompact: {
    fontSize: 12,
    includeFontPadding: false,
    lineHeight: 16,
  },
  contextGridCompact: {
    gap: 8,
  },
  heroContentCompact: {
    paddingBottom: 10,
    paddingTop: 16,
  },
  heroCtaCompact: {
    borderRadius: 22,
    height: 44,
  },
  heroCtaPressableCompact: {
    borderRadius: 22,
    marginTop: 12,
  },
  heroDescriptionCompact: {
    fontSize: 13,
    lineHeight: 20,
    marginTop: 8,
  },
  heroTitleCompact: {
    ...appTypography.displayHeroCompact,
  },
  modeCardCompact: {
    borderRadius: 16,
    gap: 4,
    height: homeUi.metrics.mode.cardHeightCompact,
  },
  modeGridCompact: {
    gap: 6,
  },
  modeIconBubbleCompact: {
    borderRadius: 16,
    height: homeUi.metrics.mode.iconCompact,
    width: homeUi.metrics.mode.iconCompact,
  },
  modeLabelCompact: {
    fontSize: 10,
  },
  recentSectionCompact: {
    gap: 9,
  },
  recentTitleCompact: {
    fontSize: 14.5,
  },
  roomAvatarCompact: {
    borderRadius: 25,
    height: 50,
    width: 50,
  },
  roomAvatarsCompact: {
    marginTop: 14,
  },
  roomCopyCompact: {
    bottom: 8,
  },
  roomDescriptionCompact: {
    fontSize: 9,
    lineHeight: 13,
    marginTop: 3,
  },
  roomHeartCompact: {
    borderRadius: 14,
    bottom: -6,
    height: 28,
    marginLeft: -14,
    width: 28,
  },
  roomTitleCompact: {
    fontSize: 11.5,
  },
  scrollContentCompact: {
    gap: appSpacing['2xl'],
    paddingTop: 7,
  },
  searchingRowCompact: {
    marginTop: 10,
  },
  sessionCtaCompact: {
    borderRadius: 17,
    height: 34,
  },
  sessionCtaPressableCompact: {
    borderRadius: 17,
    bottom: 8,
    left: 9,
    right: 9,
  },
  sessionCtaTextCompact: {
    fontSize: 12.5,
  },
  sessionReadyRowCompact: {
    marginTop: 7,
    paddingHorizontal: 9,
  },
  sessionSummaryRowCompact: {
    gap: 6,
    marginTop: 7,
    paddingHorizontal: 9,
  },
  sessionTimeBoxCompact: {
    borderRadius: 9,
    minWidth: 44,
    paddingHorizontal: 4,
    paddingVertical: 5,
  },
  sessionTimeCompact: {
    fontSize: 16,
  },
});
