#!/usr/bin/env node
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const prettier = require('prettier');

const root = process.cwd();
const manifestPath = path.join(root, 'contracts', 'core-v1', 'manifest.json');
const generatedTsPath = path.join(
  root,
  'src',
  'shared',
  'contracts',
  'core-v1',
  'generated.ts',
);
const reportPath = path.join(
  root,
  'contracts',
  'core-v1',
  'generated',
  'compatibility-report.json',
);
const check = process.argv.includes('--check');

function refName(ref) {
  const match = /^#\/schemas\/([A-Za-z0-9_]+)$/.exec(ref);
  if (!match) throw new Error(`Unsupported contract ref: ${ref}`);
  return match[1];
}

function tsType(schema) {
  if (schema.$ref) return refName(schema.$ref);
  if (schema.anyOf) return schema.anyOf.map(tsType).join(' | ');
  if (schema.enum)
    return schema.enum.map((value) => JSON.stringify(value)).join(' | ');
  if (schema.type === 'null') return 'null';
  if (schema.type === 'string') return 'string';
  if (schema.type === 'integer' || schema.type === 'number') return 'number';
  if (schema.type === 'boolean') return 'boolean';
  if (schema.type === 'array') return `readonly (${tsType(schema.items)})[]`;
  if (schema.type === 'object') {
    const required = new Set(schema.required || []);
    const properties = Object.entries(schema.properties || {}).map(
      ([key, value]) =>
        `readonly ${JSON.stringify(key)}${required.has(key) ? '' : '?'}: ${tsType(value)};`,
    );
    if (schema.additionalProperties === true)
      properties.push('readonly [key: string]: unknown;');
    return `{ ${properties.join(' ')} }`;
  }
  throw new Error(`Unsupported TypeScript schema: ${JSON.stringify(schema)}`);
}

function zodType(schema) {
  if (schema.$ref) return `z.lazy(() => ${refName(schema.$ref)}Schema)`;
  if (schema.anyOf) return `z.union([${schema.anyOf.map(zodType).join(', ')}])`;
  if (schema.enum) return `z.enum(${JSON.stringify(schema.enum)})`;
  if (schema.type === 'null') return 'z.null()';
  if (schema.type === 'string') {
    let expression = 'z.string()';
    if (schema.format === 'uuid') expression += '.uuid()';
    if (schema.format === 'date-time')
      expression += '.datetime({ offset: true })';
    if (schema.minLength !== undefined)
      expression += `.min(${schema.minLength})`;
    if (schema.maxLength !== undefined)
      expression += `.max(${schema.maxLength})`;
    if (schema.pattern)
      expression += `.regex(new RegExp(${JSON.stringify(schema.pattern)}))`;
    return expression;
  }
  if (schema.type === 'integer') {
    let expression = 'z.number().int()';
    if (schema.minimum !== undefined) expression += `.min(${schema.minimum})`;
    if (schema.maximum !== undefined) expression += `.max(${schema.maximum})`;
    return expression;
  }
  if (schema.type === 'number') return 'z.number()';
  if (schema.type === 'boolean') return 'z.boolean()';
  if (schema.type === 'array') {
    let expression = `z.array(${zodType(schema.items)})`;
    if (schema.minItems !== undefined) expression += `.min(${schema.minItems})`;
    if (schema.maxItems !== undefined) expression += `.max(${schema.maxItems})`;
    if (schema.uniqueItems) {
      expression +=
        '.refine((items) => new Set(items).size === items.length, "Array items must be unique.")';
    }
    return expression;
  }
  if (schema.type === 'object') {
    const required = new Set(schema.required || []);
    const properties = Object.entries(schema.properties || {}).map(
      ([key, value]) => {
        const expression =
          zodType(value) + (required.has(key) ? '' : '.optional()');
        return `${JSON.stringify(key)}: ${expression}`;
      },
    );
    let expression = `z.object({ ${properties.join(', ')} })`;
    expression +=
      schema.additionalProperties === true ? '.passthrough()' : '.strict()';
    return expression;
  }
  throw new Error(`Unsupported Zod schema: ${JSON.stringify(schema)}`);
}

async function main() {
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  const schemas = manifest.schemas;

  const header = `// Generated by scripts/contracts/generate-core-v1.cjs. Do not edit.\nimport { z } from 'zod';\n\nexport const CORE_V1_CONTRACT_VERSION = ${JSON.stringify(manifest.version)} as const;\n`;
  const declarations = Object.entries(schemas)
    .map(
      ([name, schema]) =>
        `\nexport type ${name} = ${tsType(schema)};\nexport const ${name}Schema: z.ZodType<${name}> = ${zodType(schema)};\n`,
    )
    .join('');
  const fixtureEntries = Object.entries(manifest.providerFixtures)
    .map(
      ([name, fixture]) =>
        `${JSON.stringify(name)}: { schema: ${JSON.stringify(fixture.schema)}, value: ${JSON.stringify(fixture.value, null, 2)} }`,
    )
    .join(',\n');
  const consumerEntries = Object.entries(manifest.consumerFixtures)
    .map(
      ([name, values]) => `${JSON.stringify(name)}: ${JSON.stringify(values)}`,
    )
    .join(',\n');
  const generatedTsRaw = `${header}${declarations}\nexport const coreV1ProviderFixtures = {\n${fixtureEntries}\n} as const;\n\nexport const coreV1ConsumerFixtures = {\n${consumerEntries}\n} as const;\n\nexport function parseCoreV1Fixture(name: keyof typeof coreV1ProviderFixtures) {\n  const fixture = coreV1ProviderFixtures[name];\n  const schema = coreV1Schemas[fixture.schema];\n  return schema.parse(fixture.value);\n}\n\nexport const coreV1Schemas = {\n${Object.keys(
    schemas,
  )
    .map((name) => `  ${name}: ${name}Schema`)
    .join(',\n')}\n} as const;\n`;

  const canonicalSchemas = Object.fromEntries(
    Object.entries(schemas).sort(([a], [b]) => a.localeCompare(b)),
  );
  const report = {
    contractSet: manifest.contractSet,
    version: manifest.version,
    status: 'initial-compatible-baseline',
    generatedAt: 'deterministic',
    schemaCount: Object.keys(schemas).length,
    fixtureCount: Object.keys(manifest.providerFixtures).length,
    breakingChanges: [],
    schemaFingerprint: crypto
      .createHash('sha256')
      .update(JSON.stringify(canonicalSchemas))
      .digest('hex'),
    schemas: Object.keys(schemas).sort(),
  };
  const reportJson = `${JSON.stringify(report, null, 2)}\n`;

  function writeOrCheck(file, content) {
    const existing = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (check) {
      if (existing !== content) {
        console.error(
          `${path.relative(root, file)} is stale. Run npm run contracts:generate.`,
        );
        process.exitCode = 1;
      }
      return;
    }
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
  }

  const prettierConfig = (await prettier.resolveConfig(generatedTsPath)) ?? {};
  const generatedTs = await prettier.format(generatedTsRaw, {
    ...prettierConfig,
    filepath: generatedTsPath,
  });

  writeOrCheck(generatedTsPath, generatedTs);
  writeOrCheck(reportPath, reportJson);
  if (!process.exitCode)
    console.log(
      check
        ? 'Core V1 generated contracts are current.'
        : 'Generated Core V1 contracts.',
    );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
