import { StyleSheet } from 'react-native';

import { liquidColors } from '@/shared/theme/liquid-glass.tokens';

export const VIBE_CARD_HEIGHT = 134;

export const exploreStyles = StyleSheet.create({
  emptyCard: { marginHorizontal: 18, marginTop: 22 },
  emptyContent: {
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  emptyReset: {
    backgroundColor: 'rgba(117,79,220,0.22)',
    borderColor: 'rgba(199,168,255,0.22)',
    borderRadius: 13,
    borderWidth: StyleSheet.hairlineWidth,
    marginTop: 13,
    paddingHorizontal: 13,
    paddingVertical: 7,
  },
  emptyResetText: {
    color: 'rgba(242,238,255,0.90)',
    fontSize: 11,
    fontWeight: '700',
  },
  emptyText: {
    color: 'rgba(196,207,238,0.62)',
    fontSize: 11,
    lineHeight: 16,
    marginTop: 5,
    textAlign: 'center',
  },
  emptyTitle: {
    color: liquidColors.text.primary,
    fontSize: 14,
    fontWeight: '700',
    marginTop: 8,
  },
  filterSummary: {
    alignItems: 'center',
    backgroundColor: 'rgba(12,18,38,0.54)',
    borderColor: 'rgba(161,145,230,0.14)',
    borderRadius: 15,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  filterSummaryCopy: { flex: 1, minWidth: 0 },
  filterSummaryLabel: {
    color: 'rgba(230,234,252,0.82)',
    fontSize: 10.5,
    fontWeight: '700',
  },
  filterSummaryQuery: {
    color: 'rgba(194,205,236,0.58)',
    fontSize: 9.5,
    marginTop: 2,
  },
  filterSummaryReset: {
    borderColor: 'rgba(208,188,255,0.18)',
    borderRadius: 11,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  filterSummaryResetText: {
    color: 'rgba(222,209,255,0.82)',
    fontSize: 9.5,
    fontWeight: '700',
  },
  fullCardSelected: {
    opacity: 0.96,
    transform: [{ scale: 0.995 }],
  },
  selectedBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(128,82,239,0.88)',
    borderColor: 'rgba(232,218,255,0.54)',
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    height: 20,
    justifyContent: 'center',
    position: 'absolute',
    right: 8,
    top: 8,
    width: 20,
  },
  avatarStack: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: 14,
  },
  avatarStackCompact: {
    justifyContent: 'flex-start',
    marginBottom: 0,
    marginTop: 9,
  },
  chatOrb: {
    alignItems: 'center',
    backgroundColor: 'rgba(14,18,34,0.58)',
    borderColor: 'rgba(225,234,255,0.13)',
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  chipList: {
    gap: 8,
    paddingHorizontal: 22,
    paddingRight: 30,
  },
  chipTextActive: { color: '#FFFFFF', fontWeight: '700' },
  compactButtonContent: {
    minHeight: 27,
    paddingHorizontal: 9,
    paddingVertical: 3.5,
  },
  compactButtonText: { color: '#FFFFFF', fontSize: 10.5, fontWeight: '800' },
  content: {
    paddingHorizontal: 0,
  },
  filterChip: {
    alignItems: 'center',
    backgroundColor: 'rgba(14,18,34,0.56)',
    borderColor: 'rgba(221,230,255,0.10)',
    borderRadius: 15,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 6,
    minHeight: 32,
    overflow: 'hidden',
    paddingHorizontal: 11,
  },
  filterChipActive: {
    backgroundColor: 'rgba(132,72,255,0.58)',
    borderColor: 'rgba(219,191,255,0.48)',
    shadowColor: '#A36CFF',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 10,
  },
  filterChipText: {
    color: 'rgba(220,226,248,0.70)',
    fontSize: 12,
    fontWeight: '600',
  },
  fullCard: { marginHorizontal: 18 },
  header: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
    paddingHorizontal: 22,
  },
  headerTitle: {
    color: liquidColors.text.primary,
    fontSize: 19,
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  matchCenter: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
    justifyContent: 'center',
    marginLeft: 8,
    minWidth: 96,
  },
  matchText: {
    color: '#C9B2FF',
    fontSize: 12,
    fontWeight: '800',
  },
  metaDot: { color: liquidColors.text.muted, fontSize: 12 },
  metricCard: { flex: 1, minWidth: 0 },
  metricCardContent: {
    alignItems: 'center',
    gap: 6,
    minHeight: 80,
    paddingHorizontal: 7,
    paddingVertical: 8,
  },
  metricIcon: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    height: 36,
    justifyContent: 'center',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    width: 36,
  },
  metricLabel: {
    color: liquidColors.text.secondary,
    fontSize: 10.5,
    fontWeight: '600',
    marginTop: 1,
    textAlign: 'center',
  },
  metricOnlineOrb: {
    backgroundColor: '#18EFB6',
    borderRadius: 999,
    height: 18,
    shadowColor: '#18EFB6',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.34,
    shadowRadius: 10,
    width: 18,
  },
  metricsRow: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 22,
  },
  metricTextBlock: { alignItems: 'center', minWidth: 0, width: '100%' },
  metricTitle: {
    color: liquidColors.text.primary,
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: -0.35,
    textAlign: 'center',
  },
  micText: { color: 'rgba(112,244,208,0.88)', fontSize: 11, fontWeight: '600' },
  onlineDot: {
    backgroundColor: '#17F4B7',
    borderColor: '#07111D',
    borderRadius: 999,
    borderWidth: 1.5,
    bottom: 3,
    height: 10,
    left: 3,
    position: 'absolute',
    width: 10,
  },
  pressed: { opacity: 0.82, transform: [{ scale: 0.99 }] },
  profileAvatar: { height: '100%', width: '100%' },
  profileActionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    width: '100%',
  },
  profileActions: {
    alignItems: 'flex-end',
    flexShrink: 0,
    gap: 5,
    width: 112,
  },
  profileAvatarShell: {
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 17,
    borderWidth: StyleSheet.hairlineWidth,
    height: 56,
    overflow: 'hidden',
    width: 56,
  },
  profileBody: { flex: 1, justifyContent: 'center', minWidth: 0 },
  profileButton: { flex: 1, minWidth: 0 },
  profileButtonContent: {
    minHeight: 32,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  profileButtonText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
  },
  profileCardContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    minHeight: 88,
    paddingHorizontal: 11,
    paddingVertical: 9,
  },
  profileCardContentCompact: {
    gap: 8,
    minHeight: 88,
    paddingHorizontal: 10,
  },
  profileMatchPill: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: 'rgba(126,86,255,0.075)',
    borderColor: 'rgba(197,166,255,0.13)',
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 3,
    justifyContent: 'center',
    minHeight: 18,
    paddingHorizontal: 5,
  },
  profileMatchText: {
    color: 'rgba(205,185,255,0.84)',
    fontSize: 9,
    fontWeight: '800',
  },
  profileName: {
    color: liquidColors.text.primary,
    flexShrink: 1,
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: -0.25,
  },
  profileNameRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
    minWidth: 0,
  },
  profileSubtitle: {
    color: liquidColors.text.secondary,
    fontSize: 12,
    marginTop: 2,
  },
  rightEdgeSheen: {
    bottom: 0,
    position: 'absolute',
    right: 0,
    top: 120,
    width: 180,
  },
  screen: { backgroundColor: '#030711', flex: 1 },
  statusBarGuard: {
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 5,
  },
  searchClearButton: {
    alignItems: 'center',
    height: 28,
    justifyContent: 'center',
    marginRight: -5,
    width: 28,
  },
  searchPlaceholder: {
    color: 'rgba(211,220,248,0.66)',
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
  },
  searchRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
    paddingHorizontal: 22,
  },
  searchShell: { flex: 1 },
  searchSurface: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minHeight: 36,
    paddingHorizontal: 11,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginBottom: 9,
    marginTop: 18,
    paddingHorizontal: 22,
  },
  sectionIconGlow: {
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.28,
    shadowRadius: 10,
  },
  sectionSpacer: { flex: 1 },
  sectionStack: { gap: 10 },
  sectionTitle: {
    color: liquidColors.text.primary,
    flexShrink: 1,
    fontSize: 14.5,
    fontWeight: '700',
    letterSpacing: -0.32,
  },
  seeAllButton: { alignItems: 'center', flexDirection: 'row', gap: 2 },
  seeAllText: {
    color: 'rgba(198,207,232,0.66)',
    fontSize: 10,
    fontWeight: '600',
  },
  setActionButton: { minWidth: 70 },
  setBody: { flex: 1, minWidth: 0 },
  setCompactRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  setTrailingCompact: {
    alignItems: 'flex-end',
    gap: 4,
    minWidth: 62,
  },
  setCardContent: {
    minHeight: 98,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  setCardContentCompact: {
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  setImage: { height: '100%', width: '100%' },
  setImageShell: {
    borderColor: 'rgba(212,223,255,0.20)',
    borderRadius: 999,
    borderWidth: 1,
    height: 46,
    overflow: 'hidden',
    width: 46,
  },
  setMeta: {
    color: liquidColors.text.secondary,
    fontSize: 11,
    fontWeight: '600',
  },
  setMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: 4,
    marginTop: 3,
  },
  setTitle: {
    color: liquidColors.text.primary,
    flex: 1,
    flexShrink: 1,
    fontSize: 13.5,
    fontWeight: '900',
    letterSpacing: -0.28,
    lineHeight: 15,
  },
  setTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
    minWidth: 0,
  },
  sliderShell: {
    borderRadius: 18,
    position: 'relative',
    width: 40,
  },
  sliderShellActive: {
    shadowColor: '#A36CFF',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.24,
    shadowRadius: 10,
  },
  filterCountBadge: {
    alignItems: 'center',
    backgroundColor: '#8C5BFF',
    borderColor: 'rgba(242,234,255,0.78)',
    borderRadius: 8,
    borderWidth: 1,
    height: 16,
    justifyContent: 'center',
    minWidth: 16,
    paddingHorizontal: 3,
    position: 'absolute',
    right: -5,
    top: -5,
  },
  filterCountText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '900',
    lineHeight: 11,
  },
  sliderSurface: {
    alignItems: 'center',
    height: 40,
    justifyContent: 'center',
    padding: 0,
  },
  stackAvatar: {
    borderColor: 'rgba(232,238,255,0.38)',
    borderRadius: 999,
    borderWidth: 1,
    height: 30,
    width: 30,
  },
  stackAvatarCompact: {
    borderColor: 'rgba(245,248,255,0.62)',
    borderWidth: 1.2,
    height: 21,
    width: 21,
  },
  stackAvatarOverlap: { marginLeft: -9 },
  stackAvatarOverlapCompact: { marginLeft: -6 },
  stackSurplus: {
    alignItems: 'center',
    backgroundColor: 'rgba(31,36,62,0.86)',
    borderColor: 'rgba(220,228,255,0.16)',
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    height: 30,
    justifyContent: 'center',
    marginLeft: -9,
    minWidth: 30,
    paddingHorizontal: 7,
  },
  stackSurplusCompact: {
    height: 21,
    marginLeft: -5,
    minWidth: 28,
    paddingHorizontal: 7,
  },
  stackSurplusText: {
    color: liquidColors.text.secondary,
    fontSize: 11,
    fontWeight: '800',
  },
  stackSurplusTextCompact: {
    color: 'rgba(237,242,255,0.84)',
    fontSize: 10,
  },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginTop: 6 },
  tagRowTight: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginTop: 5 },
  tinyTag: {
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    flexShrink: 1,
    maxWidth: '100%',
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  tinyTagText: { fontSize: 9, fontWeight: '700' },
  toneBadge: {
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    flexShrink: 0,
    gap: 3,
    paddingHorizontal: 3.25,
    paddingVertical: 1.75,
  },
  toneBadgeText: { fontSize: 7.6, fontWeight: '800' },
  topSheen: {
    height: 260,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  vibeAvatarWrap: { marginTop: 4 },
  vibeBackgroundLayer: {
    left: 0,
    position: 'absolute',
    top: 0,
  },
  vibeCard: {
    backgroundColor: 'rgba(4,7,16,0.92)',
    borderColor: 'rgba(204,222,255,0.18)',
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    height: VIBE_CARD_HEIGHT,
    overflow: 'hidden',
    position: 'relative',
  },
  vibeCardSelected: {
    borderColor: 'rgba(211,183,255,0.66)',
    borderWidth: 1,
  },
  vibeContentCluster: {
    bottom: 0,
    left: 0,
    padding: 11,
    position: 'absolute',
    right: 0,
  },
  vibeGradientLayer: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  vibeList: {
    gap: 10,
    paddingHorizontal: 22,
    paddingRight: 28,
  },
  vibeMeta: {
    color: 'rgba(239,243,255,0.78)',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 1,
    textShadowColor: 'rgba(0,0,0,0.48)',
    textShadowOffset: { height: 1, width: 0 },
    textShadowRadius: 3,
  },
  vibeTextBlock: { justifyContent: 'flex-end' },
  vibeTitle: {
    color: liquidColors.text.primary,
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: -0.34,
    textShadowColor: 'rgba(0,0,0,0.62)',
    textShadowOffset: { height: 1, width: 0 },
    textShadowRadius: 4,
  },
});
