import type { HeroClassSlug } from './hero-class-catalog';

export type HeroDomainDefinition = Readonly<{
  classSlug: HeroClassSlug;
  id: string;
  legacySlug: string;
  name: string;
}>;

/** Asset-free hero identity catalog used by contracts and backend adapters. */
export const HERO_DOMAIN_CATALOG = [
  {
    classSlug: 'marksman',
    id: 'flowborn',
    legacySlug: 'flowborn',
    name: 'Flowborn',
  },
  {
    classSlug: 'mage',
    id: 'flowborn-phep',
    legacySlug: 'flowborn_phep',
    name: 'Flowborn Phép',
  },
  {
    classSlug: 'support',
    id: 'dyadia',
    legacySlug: 'dyadia',
    name: 'Dyadia',
  },
  {
    classSlug: 'fighter',
    id: 'edras',
    legacySlug: 'edras',
    name: 'Edras',
  },
  {
    classSlug: 'mage',
    id: 'goverra',
    legacySlug: 'goverra',
    name: 'Goverra',
  },
  {
    classSlug: 'mage',
    id: 'heino',
    legacySlug: 'heino',
    name: 'Heino',
  },
  {
    classSlug: 'assassin',
    id: 'billow',
    legacySlug: 'billow',
    name: 'Billow',
  },
  {
    classSlug: 'fighter',
    id: 'bolt-baron',
    legacySlug: 'bolt_baron',
    name: 'Bolt Baron',
  },
  {
    classSlug: 'fighter',
    id: 'biron',
    legacySlug: 'biron',
    name: 'Biron',
  },
  {
    classSlug: 'support',
    id: 'dolia',
    legacySlug: 'dolia',
    name: 'Dolia',
  },
  {
    classSlug: 'fighter',
    id: 'charlotte',
    legacySlug: 'charlotte',
    name: 'Charlotte',
  },
  {
    classSlug: 'fighter',
    id: 'tachi',
    legacySlug: 'tachi',
    name: 'Tachi',
  },
  {
    classSlug: 'mage',
    id: 'dirak',
    legacySlug: 'dirak',
    name: 'Dirak',
  },
  {
    classSlug: 'fighter',
    id: 'qi',
    legacySlug: 'qi',
    name: 'Qi',
  },
  {
    classSlug: 'marksman',
    id: 'erin',
    legacySlug: 'erin',
    name: 'Erin',
  },
  {
    classSlug: 'support',
    id: 'ming',
    legacySlug: 'ming',
    name: 'Ming',
  },
  {
    classSlug: 'fighter',
    id: 'bijan',
    legacySlug: 'bijan',
    name: 'Bijan',
  },
  {
    classSlug: 'mage',
    id: 'bonnie',
    legacySlug: 'bonnie',
    name: 'Bonnie',
  },
  {
    classSlug: 'marksman',
    id: 'teeri',
    legacySlug: 'teeri',
    name: 'Teeri',
  },
  {
    classSlug: 'mage',
    id: 'yue',
    legacySlug: 'yue',
    name: 'Yue',
  },
  {
    classSlug: 'fighter',
    id: 'yan',
    legacySlug: 'yan',
    name: 'Yan',
  },
  {
    classSlug: 'support',
    id: 'aya',
    legacySlug: 'aya',
    name: 'Aya',
  },
  {
    classSlug: 'assassin',
    id: 'aoi',
    legacySlug: 'aoi',
    name: 'Aoi',
  },
  {
    classSlug: 'mage',
    id: 'iggy',
    legacySlug: 'iggy',
    name: 'Iggy',
  },
  {
    classSlug: 'marksman',
    id: 'bright',
    legacySlug: 'bright',
    name: 'Bright',
  },
  {
    classSlug: 'mage',
    id: 'lorion',
    legacySlug: 'lorion',
    name: 'Lorion',
  },
  {
    classSlug: 'fighter',
    id: 'dextra',
    legacySlug: 'dextra',
    name: 'Dextra',
  },
  {
    classSlug: 'assassin',
    id: 'sinestrea',
    legacySlug: 'sinestrea',
    name: 'Sinestrea',
  },
  {
    classSlug: 'marksman',
    id: 'thorne',
    legacySlug: 'thorne',
    name: 'Thorne',
  },
  {
    classSlug: 'fighter',
    id: 'allain',
    legacySlug: 'allain',
    name: 'Allain',
  },
  {
    classSlug: 'mage',
    id: 'zata',
    legacySlug: 'zata',
    name: 'Zata',
  },
  {
    classSlug: 'support',
    id: 'rouie',
    legacySlug: 'rouie',
    name: 'Rouie',
  },
  {
    classSlug: 'marksman',
    id: 'laville',
    legacySlug: 'laville',
    name: 'Laville',
  },
  {
    classSlug: 'assassin',
    id: 'paine',
    legacySlug: 'paine',
    name: 'Paine',
  },
  {
    classSlug: 'tank',
    id: 'ata',
    legacySlug: 'ata',
    name: 'Ata',
  },
  {
    classSlug: 'assassin',
    id: 'keera',
    legacySlug: 'keera',
    name: 'Keera',
  },
  {
    classSlug: 'mage',
    id: 'ishar',
    legacySlug: 'ishar',
    name: 'Ishar',
  },
  {
    classSlug: 'marksman',
    id: 'elandorr',
    legacySlug: 'elandorr',
    name: 'Eland’orr',
  },
  {
    classSlug: 'support',
    id: 'krizzix',
    legacySlug: 'krizzix',
    name: 'Krizzix',
  },
  {
    classSlug: 'fighter',
    id: 'volkath',
    legacySlug: 'volkath',
    name: 'Volkath',
  },
  {
    classSlug: 'marksman',
    id: 'celica',
    legacySlug: 'celica',
    name: 'Celica',
  },
  {
    classSlug: 'support',
    id: 'zip',
    legacySlug: 'zip',
    name: 'Zip',
  },
  {
    classSlug: 'assassin',
    id: 'enzo',
    legacySlug: 'enzo',
    name: 'Enzo',
  },
  {
    classSlug: 'fighter',
    id: 'yena',
    legacySlug: 'yena',
    name: 'Yena',
  },
  {
    classSlug: 'fighter',
    id: 'errol',
    legacySlug: 'errol',
    name: 'Errol',
  },
  {
    classSlug: 'marksman',
    id: 'capheny',
    legacySlug: 'capheny',
    name: 'Capheny',
  },
  {
    classSlug: 'marksman',
    id: 'hayate',
    legacySlug: 'hayate',
    name: 'Hayate',
  },
  {
    classSlug: 'mage',
    id: 'darcy',
    legacySlug: 'darcy',
    name: 'D’Arcy',
  },
  {
    classSlug: 'fighter',
    id: 'veres',
    legacySlug: 'veres',
    name: 'Veres',
  },
  {
    classSlug: 'fighter',
    id: 'florentino',
    legacySlug: 'florentino',
    name: 'Florentino',
  },
  {
    classSlug: 'mage',
    id: 'sephera',
    legacySlug: 'sephera',
    name: 'Sephera',
  },
  {
    classSlug: 'assassin',
    id: 'quillen',
    legacySlug: 'quillen',
    name: 'Quillen',
  },
  {
    classSlug: 'tank',
    id: 'wiro',
    legacySlug: 'wiro',
    name: 'Wiro',
  },
  {
    classSlug: 'fighter',
    id: 'richter',
    legacySlug: 'richter',
    name: 'Richter',
  },
  {
    classSlug: 'marksman',
    id: 'elsu',
    legacySlug: 'elsu',
    name: 'Elsu',
  },
  {
    classSlug: 'tank',
    id: 'ybneth',
    legacySlug: 'ybneth',
    name: 'Y’bneth',
  },
  {
    classSlug: 'fighter',
    id: 'amily',
    legacySlug: 'amily',
    name: 'Amily',
  },
  {
    classSlug: 'support',
    id: 'annette',
    legacySlug: 'annette',
    name: 'Annette',
  },
  {
    classSlug: 'tank',
    id: 'baldum',
    legacySlug: 'baldum',
    name: 'Baldum',
  },
  {
    classSlug: 'tank',
    id: 'roxie',
    legacySlug: 'roxie',
    name: 'Roxie',
  },
  {
    classSlug: 'mage',
    id: 'marja',
    legacySlug: 'marja',
    name: 'Marja',
  },
  {
    classSlug: 'marksman',
    id: 'rourke',
    legacySlug: 'rourke',
    name: 'Rourke',
  },
  {
    classSlug: 'tank',
    id: 'arum',
    legacySlug: 'arum',
    name: 'Arum',
  },
  {
    classSlug: 'marksman',
    id: 'wisp',
    legacySlug: 'wisp',
    name: 'Wisp',
  },
  {
    classSlug: 'mage',
    id: 'the-flash',
    legacySlug: 'the_flash',
    name: 'The Flash',
  },
  {
    classSlug: 'fighter',
    id: 'max',
    legacySlug: 'max',
    name: 'Max',
  },
  {
    classSlug: 'mage',
    id: 'liliana',
    legacySlug: 'liliana',
    name: 'Liliana',
  },
  {
    classSlug: 'mage',
    id: 'tulen',
    legacySlug: 'tulen',
    name: 'Tulen',
  },
  {
    classSlug: 'fighter',
    id: 'omen',
    legacySlug: 'omen',
    name: 'Omen',
  },
  {
    classSlug: 'marksman',
    id: 'lindis',
    legacySlug: 'lindis',
    name: 'Lindis',
  },
  {
    classSlug: 'support',
    id: 'teemee',
    legacySlug: 'teemee',
    name: 'TeeMee',
  },
  {
    classSlug: 'marksman',
    id: 'moren',
    legacySlug: 'moren',
    name: 'Moren',
  },
  {
    classSlug: 'fighter',
    id: 'kilgroth',
    legacySlug: 'kilgroth',
    name: 'Kil’Groth',
  },
  {
    classSlug: 'tank',
    id: 'xeniel',
    legacySlug: 'xeniel',
    name: 'Xeniel',
  },
  {
    classSlug: 'fighter',
    id: 'wonder-woman',
    legacySlug: 'wonder_woman',
    name: 'Wonder Woman',
  },
  {
    classSlug: 'fighter',
    id: 'superman',
    legacySlug: 'superman',
    name: 'Superman',
  },
  {
    classSlug: 'marksman',
    id: 'telannas',
    legacySlug: 'telannas',
    name: 'Tel’Annas',
  },
  {
    classSlug: 'fighter',
    id: 'astrid',
    legacySlug: 'astrid',
    name: 'Astrid',
  },
  {
    classSlug: 'fighter',
    id: 'ryoma',
    legacySlug: 'ryoma',
    name: 'Ryoma',
  },
  {
    classSlug: 'marksman',
    id: 'stuart',
    legacySlug: 'stuart',
    name: 'Stuart',
  },
  {
    classSlug: 'tank',
    id: 'arduin',
    legacySlug: 'arduin',
    name: 'Arduin',
  },
  {
    classSlug: 'assassin',
    id: 'zill',
    legacySlug: 'zill',
    name: 'Zill',
  },
  {
    classSlug: 'assassin',
    id: 'murad',
    legacySlug: 'murad',
    name: 'Murad',
  },
  {
    classSlug: 'mage',
    id: 'ignis',
    legacySlug: 'ignis',
    name: 'Ignis',
  },
  {
    classSlug: 'fighter',
    id: 'zuka',
    legacySlug: 'zuka',
    name: 'Zuka',
  },
  {
    classSlug: 'fighter',
    id: 'airi',
    legacySlug: 'airi',
    name: 'Airi',
  },
  {
    classSlug: 'assassin',
    id: 'kaine',
    legacySlug: 'kaine',
    name: 'Kaine',
  },
  {
    classSlug: 'mage',
    id: 'lauriel',
    legacySlug: 'lauriel',
    name: 'Lauriel',
  },
  {
    classSlug: 'mage',
    id: 'raz',
    legacySlug: 'raz',
    name: 'Raz',
  },
  {
    classSlug: 'fighter',
    id: 'skud',
    legacySlug: 'skud',
    name: 'Skud',
  },
  {
    classSlug: 'mage',
    id: 'preyta',
    legacySlug: 'preyta',
    name: 'Preyta',
  },
  {
    classSlug: 'mage',
    id: 'ilumia',
    legacySlug: 'ilumia',
    name: 'Ilumia',
  },
  {
    classSlug: 'marksman',
    id: 'slimz',
    legacySlug: 'slimz',
    name: 'Slimz',
  },
  {
    classSlug: 'fighter',
    id: 'arthur',
    legacySlug: 'arthur',
    name: 'Arthur',
  },
  {
    classSlug: 'assassin',
    id: 'kriknak',
    legacySlug: 'kriknak',
    name: 'Kriknak',
  },
  {
    classSlug: 'assassin',
    id: 'ngo-khong',
    legacySlug: 'ngo_khong',
    name: 'Ngộ Không',
  },
  {
    classSlug: 'fighter',
    id: 'maloch',
    legacySlug: 'maloch',
    name: 'Maloch',
  },
  {
    classSlug: 'support',
    id: 'helen',
    legacySlug: 'helen',
    name: 'Helen',
  },
  {
    classSlug: 'mage',
    id: 'jinna',
    legacySlug: 'jinna',
    name: 'Jinna',
  },
  {
    classSlug: 'tank',
    id: 'cresht',
    legacySlug: 'cresht',
    name: 'Cresht',
  },
  {
    classSlug: 'mage',
    id: 'natalya',
    legacySlug: 'natalya',
    name: 'Natalya',
  },
  {
    classSlug: 'tank',
    id: 'lumburr',
    legacySlug: 'lumburr',
    name: 'Lumburr',
  },
  {
    classSlug: 'marksman',
    id: 'fennik',
    legacySlug: 'fennik',
    name: 'Fennik',
  },
  {
    classSlug: 'mage',
    id: 'aleister',
    legacySlug: 'aleister',
    name: 'Aleister',
  },
  {
    classSlug: 'tank',
    id: 'grakk',
    legacySlug: 'grakk',
    name: 'Grakk',
  },
  {
    classSlug: 'assassin',
    id: 'nakroth',
    legacySlug: 'nakroth',
    name: 'Nakroth',
  },
  {
    classSlug: 'tank',
    id: 'taara',
    legacySlug: 'taara',
    name: 'Taara',
  },
  {
    classSlug: 'tank',
    id: 'toro',
    legacySlug: 'toro',
    name: 'Toro',
  },
  {
    classSlug: 'marksman',
    id: 'yorn',
    legacySlug: 'yorn',
    name: 'Yorn',
  },
  {
    classSlug: 'tank',
    id: 'gildur',
    legacySlug: 'gildur',
    name: 'Gildur',
  },
  {
    classSlug: 'support',
    id: 'alice',
    legacySlug: 'alice',
    name: 'Alice',
  },
  {
    classSlug: 'mage',
    id: 'azzenka',
    legacySlug: 'azzenka',
    name: 'Azzen’Ka',
  },
  {
    classSlug: 'tank',
    id: 'ormarr',
    legacySlug: 'ormarr',
    name: 'Ormarr',
  },
  {
    classSlug: 'assassin',
    id: 'butterfly',
    legacySlug: 'butterfly',
    name: 'Butterfly',
  },
  {
    classSlug: 'marksman',
    id: 'violet',
    legacySlug: 'violet',
    name: 'Violet',
  },
  {
    classSlug: 'support',
    id: 'chaugnar',
    legacySlug: 'chaugnar',
    name: 'Chaugnar',
  },
  {
    classSlug: 'mage',
    id: 'dieu-thuyen',
    legacySlug: 'dieu_thuyen',
    name: 'Điêu Thuyền',
  },
  {
    classSlug: 'assassin',
    id: 'zephys',
    legacySlug: 'zephys',
    name: 'Zephys',
  },
  {
    classSlug: 'mage',
    id: 'kahlii',
    legacySlug: 'kahlii',
    name: 'Kahlii',
  },
  {
    classSlug: 'tank',
    id: 'omega',
    legacySlug: 'omega',
    name: 'Omega',
  },
  {
    classSlug: 'fighter',
    id: 'trieu-van',
    legacySlug: 'trieu_van',
    name: 'Triệu Vân',
  },
  {
    classSlug: 'mage',
    id: 'mganga',
    legacySlug: 'mganga',
    name: 'Mganga',
  },
  {
    classSlug: 'mage',
    id: 'krixi',
    legacySlug: 'krixi',
    name: 'Krixi',
  },
  {
    classSlug: 'tank',
    id: 'mina',
    legacySlug: 'mina',
    name: 'Mina',
  },
  {
    classSlug: 'fighter',
    id: 'lu-bo',
    legacySlug: 'lu_bo',
    name: 'Lữ Bố',
  },
  {
    classSlug: 'mage',
    id: 'veera',
    legacySlug: 'veera',
    name: 'Veera',
  },
  {
    classSlug: 'tank',
    id: 'thane',
    legacySlug: 'thane',
    name: 'Thane',
  },
  {
    classSlug: 'marksman',
    id: 'valhein',
    legacySlug: 'valhein',
    name: 'Valhein',
  },
] as const satisfies readonly HeroDomainDefinition[];

export type HeroId = (typeof HERO_DOMAIN_CATALOG)[number]['id'];

export const HERO_IDS = HERO_DOMAIN_CATALOG.map((hero) => hero.id);

export function heroDefinitionById(id: string) {
  return HERO_DOMAIN_CATALOG.find((hero) => hero.id === id);
}
