// Generated by scripts/generate-asset-manifest.cjs. Do not edit manually.
export const bundledModuleByAssetKey = {
  'asset:profile:an-mage:avatar':
    require('../../../../assets/simulation/golden-world/avatars/lavender-mage.webp') as number,
  'asset:profile:duc-flex:avatar':
    require('../../../../assets/simulation/golden-world/avatars/silver-assassin.webp') as number,
  'asset:profile:huy-captain:avatar':
    require('../../../../assets/simulation/golden-world/avatars/dark-fighter.webp') as number,
  'asset:profile:khoa-jungle:avatar':
    require('../../../../assets/simulation/golden-world/avatars/khoa-jungle.webp') as number,
  'asset:profile:linh-mid:avatar':
    require('../../../../assets/simulation/golden-world/avatars/cyber-girl.webp') as number,
  'asset:profile:minh-anh:avatar':
    require('../../../../assets/simulation/golden-world/avatars/minh-anh.webp') as number,
  'asset:profile:nam-slayer:avatar':
    require('../../../../assets/simulation/golden-world/avatars/ice-prince.webp') as number,
  'asset:profile:phuc-jungle:avatar':
    require('../../../../assets/simulation/golden-world/avatars/phuc-jungle.webp') as number,
  'asset:profile:quan-viewer:avatar':
    require('../../../../assets/simulation/golden-world/avatars/cozy-gamer.webp') as number,
  'asset:profile:trang-carry:avatar':
    require('../../../../assets/simulation/golden-world/avatars/pink-support.webp') as number,
  'asset:profile:vy-carry:avatar':
    require('../../../../assets/simulation/golden-world/avatars/pink-carry.webp') as number,
  'asset:profile:quan-viewer:cover':
    require('../../../../assets/simulation/golden-world/covers/quan-viewer.webp') as number,
  'asset:profile:minh-anh:cover':
    require('../../../../assets/simulation/golden-world/covers/minh-anh.webp') as number,
  'asset:profile:khoa-jungle:cover':
    require('../../../../assets/simulation/golden-world/covers/khoa-jungle.webp') as number,
  'asset:profile:quan-viewer:wall:0':
    require('../../../../assets/simulation/golden-world/walls/quan-viewer-rank.webp') as number,
  'asset:profile:quan-viewer:wall:1':
    require('../../../../assets/simulation/golden-world/walls/quan-viewer-team.webp') as number,
  'asset:profile:quan-viewer:cover-pending':
    require('../../../../assets/simulation/golden-world/covers/quan-viewer-pending.webp') as number,
  'asset:set:dem-violet:artwork':
    require('../../../../assets/simulation/golden-world/artwork/set-dem-violet.webp') as number,
  'asset:set:sao-bang:artwork':
    require('../../../../assets/simulation/golden-world/artwork/set-team-sao-bang.webp') as number,
  'asset:set:macro-lab:artwork':
    require('../../../../assets/simulation/golden-world/artwork/set-duo-jungle-support.webp') as number,
  'asset:vibe:rank:artwork':
    require('../../../../assets/simulation/golden-world/artwork/vibe-late-night-rank.webp') as number,
  'asset:vibe:social:artwork':
    require('../../../../assets/simulation/golden-world/artwork/vibe-duo-support.webp') as number,
  'asset:vibe:team:artwork':
    require('../../../../assets/simulation/golden-world/artwork/vibe-team-needs-mid.webp') as number,
  'asset:message:victory-photo':
    require('../../../../assets/simulation/golden-world/messages/victory-photo.webp') as number,
  'asset:message:lobby-screenshot':
    require('../../../../assets/simulation/golden-world/messages/lobby-screenshot.webp') as number,
  'asset:message:build-aya':
    require('../../../../assets/anh_mau2/heroes/aya.webp') as number,
  'asset:shared:role-support':
    require('../../../../assets/anh_mau2/lane-icons/support.png') as number,
  'asset:shared:legacy-build-nakroth':
    require('../../../../assets/anh_mau2/heroes/nakroth.webp') as number,
  'asset:shared:legacy-role-jungle':
    require('../../../../assets/anh_mau2/lane-icons/jungle.png') as number,
} as const;
