import { StyleSheet } from 'react-native';

import { liqiColors } from '@/shared/theme/liqi-design-system';

export const discoverCollectionStyles = StyleSheet.create({
  actionButton: { minWidth: 116 },
  actionButtonContent: {
    minHeight: 35,
    paddingHorizontal: 14,
    paddingVertical: 5,
  },
  actionButtonText: { color: '#FFFFFF', fontSize: 11, fontWeight: '800' },
  avatarStack: { alignItems: 'center', flexDirection: 'row' },
  backButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(13,18,36,0.58)',
    borderColor: 'rgba(225,232,255,0.12)',
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  cardFooter: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  clearButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 999,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  collectionCard: { marginHorizontal: 0 },
  content: { paddingHorizontal: 0 },
  emptyCard: { marginTop: 20 },
  emptyContent: {
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 28,
  },
  emptyReset: {
    backgroundColor: 'rgba(117,79,220,0.22)',
    borderColor: 'rgba(199,168,255,0.22)',
    borderRadius: 13,
    borderWidth: StyleSheet.hairlineWidth,
    marginTop: 14,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  emptyResetText: { color: '#F0E9FF', fontSize: 11, fontWeight: '800' },
  emptyText: {
    color: 'rgba(196,207,238,0.62)',
    fontSize: 11,
    lineHeight: 17,
    marginTop: 5,
    textAlign: 'center',
  },
  emptyTitle: {
    color: liqiColors.text.primary,
    fontSize: 15,
    fontWeight: '800',
    marginTop: 9,
  },
  filterChip: {
    alignItems: 'center',
    backgroundColor: 'rgba(14,18,34,0.56)',
    borderColor: 'rgba(221,230,255,0.10)',
    borderRadius: 15,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 6,
    minHeight: 31,
    paddingHorizontal: 10,
  },
  filterChipActive: {
    backgroundColor: 'rgba(132,72,255,0.58)',
    borderColor: 'rgba(219,191,255,0.48)',
    shadowColor: '#A36CFF',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 10,
  },
  filterList: { gap: 8, paddingTop: 9 },
  filterText: {
    color: 'rgba(220,226,248,0.70)',
    fontSize: 11.5,
    fontWeight: '600',
  },
  filterTextActive: { color: '#FFFFFF', fontWeight: '800' },
  header: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    marginBottom: 10,
  },
  headerBalance: { width: 44 },
  headerCopy: { alignItems: 'center', flex: 1, minWidth: 0 },
  headerSubtitle: {
    color: 'rgba(205,214,240,0.64)',
    fontSize: 10.5,
    lineHeight: 14,
    marginTop: 2,
    textAlign: 'center',
  },
  headerTitle: {
    color: liqiColors.text.primary,
    fontSize: 17,
    fontWeight: '900',
    letterSpacing: -0.45,
  },
  list: { gap: 12, paddingHorizontal: 18, paddingTop: 4 },
  matchPill: {
    alignItems: 'center',
    backgroundColor: 'rgba(126,86,255,0.11)',
    borderColor: 'rgba(197,166,255,0.18)',
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 4,
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  matchText: { color: '#D6C1FF', fontSize: 9.25, fontWeight: '900' },
  messageButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(14,18,34,0.58)',
    borderColor: 'rgba(225,234,255,0.13)',
    borderRadius: 17,
    borderWidth: StyleSheet.hairlineWidth,
    height: 34,
    justifyContent: 'center',
    width: 38,
  },
  metaDot: { color: liqiColors.text.muted, fontSize: 12 },
  metaRow: { alignItems: 'center', flexDirection: 'row', gap: 5, marginTop: 6 },
  metaText: {
    color: 'rgba(205,213,239,0.68)',
    fontSize: 11.5,
    fontWeight: '600',
  },
  micText: { color: 'rgba(112,244,208,0.88)', fontSize: 11, fontWeight: '700' },
  onlineDot: {
    backgroundColor: '#17F4B7',
    borderColor: '#07111D',
    borderRadius: 999,
    borderWidth: 1.25,
    bottom: 3,
    height: 9,
    left: 3,
    position: 'absolute',
    width: 9,
  },
  pressed: { opacity: 0.82, transform: [{ scale: 0.99 }] },
  profileActionButton: { minWidth: 0, width: '100%' },
  profileActionWrap: { width: '58%' },
  profileActionContent: {
    minHeight: 34,
    paddingHorizontal: 13,
    paddingVertical: 4,
  },
  profileAvatar: { height: '100%', width: '100%' },
  profileAvatarShell: {
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    height: 62,
    overflow: 'hidden',
    width: 62,
  },
  profileCardContent: { paddingHorizontal: 12, paddingVertical: 11 },
  profileCopy: { flex: 1, minWidth: 0 },
  profileFooter: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 11,
    justifyContent: 'flex-end',
    marginTop: 8,
  },
  profileName: {
    color: liqiColors.text.primary,
    flexShrink: 1,
    fontSize: 16,
    fontWeight: '900',
  },
  profileNameRow: { alignItems: 'center', flexDirection: 'row', gap: 5 },
  profileTagsRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
    minWidth: 0,
    overflow: 'hidden',
  },
  profileSubtitle: {
    color: 'rgba(202,211,239,0.66)',
    fontSize: 11.5,
    marginTop: 4,
  },
  profileTopRow: { alignItems: 'center', flexDirection: 'row', gap: 11 },
  profileViewActionWrap: { width: '54%' },
  resultCopy: { flex: 1, minWidth: 0 },
  resultCount: {
    color: 'rgba(235,239,255,0.88)',
    fontSize: 12,
    fontWeight: '800',
  },
  rightSheen: {
    bottom: 0,
    position: 'absolute',
    right: 0,
    top: 180,
    width: '44%',
  },
  screen: { backgroundColor: '#030711', flex: 1 },
  searchInput: {
    color: liqiColors.text.primary,
    flex: 1,
    fontSize: 12.5,
    fontWeight: '600',
    minWidth: 0,
    paddingVertical: 0,
  },
  searchRow: { flexDirection: 'row' },
  searchSurface: { flex: 1 },
  searchSurfaceContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
    minHeight: 41,
    paddingHorizontal: 13,
  },
  selectedCard: { opacity: 0.97, transform: [{ scale: 0.997 }] },
  selectedPill: {
    alignItems: 'center',
    backgroundColor: 'rgba(126,76,238,0.80)',
    borderColor: 'rgba(234,220,255,0.42)',
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  selectedPillText: { color: '#FFFFFF', fontSize: 9.5, fontWeight: '800' },
  setCardContent: { paddingHorizontal: 13, paddingVertical: 13 },
  setCopy: { flex: 1, minWidth: 0 },
  setImage: { height: '100%', width: '100%' },
  setImageShell: {
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    height: 66,
    overflow: 'hidden',
    width: 66,
  },
  setTitle: {
    color: liqiColors.text.primary,
    flex: 1,
    fontSize: 15.5,
    fontWeight: '900',
    lineHeight: 18,
  },
  setTopRow: { alignItems: 'center', flexDirection: 'row', gap: 11 },
  sortButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(13,18,36,0.58)',
    borderColor: 'rgba(217,224,247,0.12)',
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 5,
    maxWidth: '46%',
    minHeight: 29,
    paddingHorizontal: 8,
  },
  sortLabel: {
    color: 'rgba(224,229,249,0.76)',
    flexShrink: 1,
    fontSize: 10.5,
    fontWeight: '700',
  },
  sortOption: {
    alignItems: 'center',
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 36,
    paddingHorizontal: 11,
  },
  sortOptionActive: { backgroundColor: 'rgba(127,78,228,0.18)' },
  sortOptionText: {
    color: 'rgba(207,216,242,0.66)',
    fontSize: 11,
    fontWeight: '600',
  },
  sortOptionTextActive: { color: '#E5D7FF', fontWeight: '800' },
  sortPanel: { gap: 2, padding: 7 },
  sortPanelWrap: { marginBottom: 8, marginTop: -4 },
  stackAvatar: {
    borderColor: 'rgba(233,237,255,0.56)',
    borderRadius: 999,
    borderWidth: 1,
    height: 30,
    width: 30,
  },
  stackAvatarOverlap: { marginLeft: -8 },
  stackSurplus: {
    alignItems: 'center',
    backgroundColor: 'rgba(36,43,73,0.94)',
    borderColor: 'rgba(220,225,255,0.12)',
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    height: 30,
    justifyContent: 'center',
    marginLeft: -6,
    minWidth: 36,
    paddingHorizontal: 7,
  },
  stackSurplusText: {
    color: 'rgba(238,240,255,0.84)',
    fontSize: 10.5,
    fontWeight: '900',
  },
  statusGuard: { left: 0, position: 'absolute', right: 0, top: 0, zIndex: 8 },
  tagsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 10 },
  tinyTag: {
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    maxWidth: '100%',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  tinyTagText: { fontSize: 9.5, fontWeight: '700' },
  titleBadgeRow: { alignItems: 'flex-start', flexDirection: 'row', gap: 8 },
  toneBadge: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 4,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  toneBadgeText: { fontSize: 9, fontWeight: '800' },
  toolbar: {
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 11,
    paddingBottom: 8,
  },
  topSheen: { height: 480, left: 0, position: 'absolute', right: 0, top: 0 },
  vibeBottom: { bottom: 13, left: 14, position: 'absolute', right: 14 },
  vibeCard: {
    borderColor: 'rgba(220,225,255,0.12)',
    borderRadius: 23,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
    position: 'relative',
  },
  vibeArtwork: { bottom: 0, position: 'absolute', right: 0, top: 0 },
  vibeBackdrop: {
    bottom: 0,
    left: 0,
    opacity: 0.42,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  vibeMeta: {
    color: 'rgba(226,230,247,0.76)',
    fontSize: 11.5,
    fontWeight: '600',
    marginTop: 3,
  },
  vibeTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: -0.4,
  },
  vibeSelection: {
    alignItems: 'flex-end',
    left: 12,
    position: 'absolute',
    right: 12,
    top: 12,
  },
});
