import type { ImageSourcePropType } from 'react-native';

export type HeroRole =
  'Tất cả' | 'Đấu sĩ' | 'Đỡ đòn' | 'Pháp sư' | 'Sát thủ' | 'Trợ thủ' | 'Xạ thủ';

export type Hero = {
  id: string;
  name: string;
  role: Exclude<HeroRole, 'Tất cả'>;
  image: ImageSourcePropType;
  variant?: string;
};

export const HERO_ROLES: HeroRole[] = [
  'Tất cả',
  'Đấu sĩ',
  'Đỡ đòn',
  'Pháp sư',
  'Sát thủ',
  'Trợ thủ',
  'Xạ thủ',
];

export const HEROES: Hero[] = [
  {
    id: 'flowborn',
    name: 'Flowborn',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/flowborn.webp'),
    variant: 'Xạ Thủ',
  },
  {
    id: 'flowborn-phep',
    name: 'Flowborn Phép',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/flowborn-phep.webp'),
    variant: 'Pháp Sư',
  },
  {
    id: 'dyadia',
    name: 'Dyadia',
    role: 'Trợ thủ',
    image: require('../../../assets/anh_mau2/heroes/dyadia.webp'),
    variant: 'Trợ Thủ / Pháp Sư',
  },
  {
    id: 'edras',
    name: 'Edras',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/edras.jpg'),
  },
  {
    id: 'goverra',
    name: 'Goverra',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/goverra.webp'),
  },
  {
    id: 'heino',
    name: 'Heino',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/heino.webp'),
  },
  {
    id: 'billow',
    name: 'Billow',
    role: 'Sát thủ',
    image: require('../../../assets/anh_mau2/heroes/billow.webp'),
  },
  {
    id: 'bolt-baron',
    name: 'Bolt Baron',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/bolt-baron.webp'),
  },
  {
    id: 'biron',
    name: 'Biron',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/biron.webp'),
  },
  {
    id: 'dolia',
    name: 'Dolia',
    role: 'Trợ thủ',
    image: require('../../../assets/anh_mau2/heroes/dolia.webp'),
  },
  {
    id: 'charlotte',
    name: 'Charlotte',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/charlotte.webp'),
  },
  {
    id: 'tachi',
    name: 'Tachi',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/tachi.webp'),
  },
  {
    id: 'dirak',
    name: 'Dirak',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/dirak.webp'),
  },
  {
    id: 'qi',
    name: 'Qi',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/qi.webp'),
  },
  {
    id: 'erin',
    name: 'Erin',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/erin.webp'),
  },
  {
    id: 'ming',
    name: 'Ming',
    role: 'Trợ thủ',
    image: require('../../../assets/anh_mau2/heroes/ming.webp'),
  },
  {
    id: 'bijan',
    name: 'Bijan',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/bijan.webp'),
  },
  {
    id: 'bonnie',
    name: 'Bonnie',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/bonnie.webp'),
  },
  {
    id: 'teeri',
    name: 'Teeri',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/teeri.webp'),
  },
  {
    id: 'yue',
    name: 'Yue',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/yue.webp'),
  },
  {
    id: 'yan',
    name: 'Yan',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/yan.webp'),
  },
  {
    id: 'aya',
    name: 'Aya',
    role: 'Trợ thủ',
    image: require('../../../assets/anh_mau2/heroes/aya.webp'),
  },
  {
    id: 'aoi',
    name: 'Aoi',
    role: 'Sát thủ',
    image: require('../../../assets/anh_mau2/heroes/aoi.webp'),
  },
  {
    id: 'iggy',
    name: 'Iggy',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/iggy.webp'),
  },
  {
    id: 'bright',
    name: 'Bright',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/bright.webp'),
  },
  {
    id: 'lorion',
    name: 'Lorion',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/lorion.webp'),
  },
  {
    id: 'dextra',
    name: 'Dextra',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/dextra.webp'),
  },
  {
    id: 'sinestrea',
    name: 'Sinestrea',
    role: 'Sát thủ',
    image: require('../../../assets/anh_mau2/heroes/sinestrea.webp'),
  },
  {
    id: 'thorne',
    name: 'Thorne',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/thorne.webp'),
  },
  {
    id: 'allain',
    name: 'Allain',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/allain.webp'),
  },
  {
    id: 'zata',
    name: 'Zata',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/zata.webp'),
  },
  {
    id: 'rouie',
    name: 'Rouie',
    role: 'Trợ thủ',
    image: require('../../../assets/anh_mau2/heroes/rouie.webp'),
  },
  {
    id: 'laville',
    name: 'Laville',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/laville.webp'),
  },
  {
    id: 'paine',
    name: 'Paine',
    role: 'Sát thủ',
    image: require('../../../assets/anh_mau2/heroes/paine.webp'),
  },
  {
    id: 'ata',
    name: 'Ata',
    role: 'Đỡ đòn',
    image: require('../../../assets/anh_mau2/heroes/ata.webp'),
  },
  {
    id: 'keera',
    name: 'Keera',
    role: 'Sát thủ',
    image: require('../../../assets/anh_mau2/heroes/keera.webp'),
  },
  {
    id: 'ishar',
    name: 'Ishar',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/ishar.webp'),
  },
  {
    id: 'elandorr',
    name: 'Eland’orr',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/elandorr.webp'),
  },
  {
    id: 'krizzix',
    name: 'Krizzix',
    role: 'Trợ thủ',
    image: require('../../../assets/anh_mau2/heroes/krizzix.webp'),
  },
  {
    id: 'volkath',
    name: 'Volkath',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/volkath.webp'),
  },
  {
    id: 'celica',
    name: 'Celica',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/celica.webp'),
  },
  {
    id: 'zip',
    name: 'Zip',
    role: 'Trợ thủ',
    image: require('../../../assets/anh_mau2/heroes/zip.webp'),
  },
  {
    id: 'enzo',
    name: 'Enzo',
    role: 'Sát thủ',
    image: require('../../../assets/anh_mau2/heroes/enzo.webp'),
  },
  {
    id: 'yena',
    name: 'Yena',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/yena.webp'),
  },
  {
    id: 'errol',
    name: 'Errol',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/errol.webp'),
  },
  {
    id: 'capheny',
    name: 'Capheny',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/capheny.webp'),
  },
  {
    id: 'hayate',
    name: 'Hayate',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/hayate.webp'),
  },
  {
    id: 'darcy',
    name: 'D’Arcy',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/darcy.webp'),
  },
  {
    id: 'veres',
    name: 'Veres',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/veres.webp'),
  },
  {
    id: 'florentino',
    name: 'Florentino',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/florentino.webp'),
  },
  {
    id: 'sephera',
    name: 'Sephera',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/sephera.webp'),
  },
  {
    id: 'quillen',
    name: 'Quillen',
    role: 'Sát thủ',
    image: require('../../../assets/anh_mau2/heroes/quillen.webp'),
  },
  {
    id: 'wiro',
    name: 'Wiro',
    role: 'Đỡ đòn',
    image: require('../../../assets/anh_mau2/heroes/wiro.webp'),
  },
  {
    id: 'richter',
    name: 'Richter',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/richter.webp'),
  },
  {
    id: 'elsu',
    name: 'Elsu',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/elsu.webp'),
  },
  {
    id: 'ybneth',
    name: 'Y’bneth',
    role: 'Đỡ đòn',
    image: require('../../../assets/anh_mau2/heroes/ybneth.webp'),
  },
  {
    id: 'amily',
    name: 'Amily',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/amily.webp'),
  },
  {
    id: 'annette',
    name: 'Annette',
    role: 'Trợ thủ',
    image: require('../../../assets/anh_mau2/heroes/annette.webp'),
  },
  {
    id: 'baldum',
    name: 'Baldum',
    role: 'Đỡ đòn',
    image: require('../../../assets/anh_mau2/heroes/baldum.webp'),
  },
  {
    id: 'roxie',
    name: 'Roxie',
    role: 'Đỡ đòn',
    image: require('../../../assets/anh_mau2/heroes/roxie.webp'),
  },
  {
    id: 'marja',
    name: 'Marja',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/marja.webp'),
  },
  {
    id: 'rourke',
    name: 'Rourke',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/rourke.webp'),
  },
  {
    id: 'arum',
    name: 'Arum',
    role: 'Đỡ đòn',
    image: require('../../../assets/anh_mau2/heroes/arum.webp'),
  },
  {
    id: 'wisp',
    name: 'Wisp',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/wisp.webp'),
  },
  {
    id: 'the-flash',
    name: 'The Flash',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/the-flash.webp'),
  },
  {
    id: 'max',
    name: 'Max',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/max.webp'),
  },
  {
    id: 'liliana',
    name: 'Liliana',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/liliana.webp'),
  },
  {
    id: 'tulen',
    name: 'Tulen',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/tulen.webp'),
  },
  {
    id: 'omen',
    name: 'Omen',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/omen.webp'),
  },
  {
    id: 'lindis',
    name: 'Lindis',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/lindis.webp'),
  },
  {
    id: 'teemee',
    name: 'TeeMee',
    role: 'Trợ thủ',
    image: require('../../../assets/anh_mau2/heroes/teemee.webp'),
  },
  {
    id: 'moren',
    name: 'Moren',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/moren.webp'),
  },
  {
    id: 'kilgroth',
    name: 'Kil’Groth',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/kilgroth.webp'),
  },
  {
    id: 'xeniel',
    name: 'Xeniel',
    role: 'Đỡ đòn',
    image: require('../../../assets/anh_mau2/heroes/xeniel.webp'),
  },
  {
    id: 'wonder-woman',
    name: 'Wonder Woman',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/wonder-woman.webp'),
  },
  {
    id: 'superman',
    name: 'Superman',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/superman.webp'),
  },
  {
    id: 'telannas',
    name: 'Tel’Annas',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/telannas.webp'),
  },
  {
    id: 'astrid',
    name: 'Astrid',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/astrid.webp'),
  },
  {
    id: 'ryoma',
    name: 'Ryoma',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/ryoma.webp'),
  },
  {
    id: 'stuart',
    name: 'Stuart',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/stuart.webp'),
  },
  {
    id: 'arduin',
    name: 'Arduin',
    role: 'Đỡ đòn',
    image: require('../../../assets/anh_mau2/heroes/arduin.webp'),
  },
  {
    id: 'zill',
    name: 'Zill',
    role: 'Sát thủ',
    image: require('../../../assets/anh_mau2/heroes/zill.webp'),
  },
  {
    id: 'murad',
    name: 'Murad',
    role: 'Sát thủ',
    image: require('../../../assets/anh_mau2/heroes/murad.webp'),
  },
  {
    id: 'ignis',
    name: 'Ignis',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/ignis.webp'),
  },
  {
    id: 'zuka',
    name: 'Zuka',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/zuka.webp'),
  },
  {
    id: 'airi',
    name: 'Airi',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/airi.webp'),
  },
  {
    id: 'kaine',
    name: 'Kaine',
    role: 'Sát thủ',
    image: require('../../../assets/anh_mau2/heroes/kaine.webp'),
  },
  {
    id: 'lauriel',
    name: 'Lauriel',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/lauriel.webp'),
  },
  {
    id: 'raz',
    name: 'Raz',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/raz.webp'),
  },
  {
    id: 'skud',
    name: 'Skud',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/skud.webp'),
  },
  {
    id: 'preyta',
    name: 'Preyta',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/preyta.webp'),
  },
  {
    id: 'ilumia',
    name: 'Ilumia',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/ilumia.webp'),
  },
  {
    id: 'slimz',
    name: 'Slimz',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/slimz.webp'),
  },
  {
    id: 'arthur',
    name: 'Arthur',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/arthur.webp'),
  },
  {
    id: 'kriknak',
    name: 'Kriknak',
    role: 'Sát thủ',
    image: require('../../../assets/anh_mau2/heroes/kriknak.webp'),
  },
  {
    id: 'ngo-khong',
    name: 'Ngộ Không',
    role: 'Sát thủ',
    image: require('../../../assets/anh_mau2/heroes/ngo-khong.webp'),
  },
  {
    id: 'maloch',
    name: 'Maloch',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/maloch.webp'),
  },
  {
    id: 'helen',
    name: 'Helen',
    role: 'Trợ thủ',
    image: require('../../../assets/anh_mau2/heroes/helen.webp'),
  },
  {
    id: 'jinna',
    name: 'Jinna',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/jinna.webp'),
  },
  {
    id: 'cresht',
    name: 'Cresht',
    role: 'Đỡ đòn',
    image: require('../../../assets/anh_mau2/heroes/cresht.webp'),
  },
  {
    id: 'natalya',
    name: 'Natalya',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/natalya.webp'),
  },
  {
    id: 'lumburr',
    name: 'Lumburr',
    role: 'Đỡ đòn',
    image: require('../../../assets/anh_mau2/heroes/lumburr.webp'),
  },
  {
    id: 'fennik',
    name: 'Fennik',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/fennik.webp'),
  },
  {
    id: 'aleister',
    name: 'Aleister',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/aleister.webp'),
  },
  {
    id: 'grakk',
    name: 'Grakk',
    role: 'Đỡ đòn',
    image: require('../../../assets/anh_mau2/heroes/grakk.webp'),
  },
  {
    id: 'nakroth',
    name: 'Nakroth',
    role: 'Sát thủ',
    image: require('../../../assets/anh_mau2/heroes/nakroth.webp'),
  },
  {
    id: 'taara',
    name: 'Taara',
    role: 'Đỡ đòn',
    image: require('../../../assets/anh_mau2/heroes/taara.webp'),
  },
  {
    id: 'toro',
    name: 'Toro',
    role: 'Đỡ đòn',
    image: require('../../../assets/anh_mau2/heroes/toro.webp'),
  },
  {
    id: 'yorn',
    name: 'Yorn',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/yorn.webp'),
  },
  {
    id: 'gildur',
    name: 'Gildur',
    role: 'Đỡ đòn',
    image: require('../../../assets/anh_mau2/heroes/gildur.webp'),
  },
  {
    id: 'alice',
    name: 'Alice',
    role: 'Trợ thủ',
    image: require('../../../assets/anh_mau2/heroes/alice.webp'),
  },
  {
    id: 'azzenka',
    name: 'Azzen’Ka',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/azzenka.webp'),
  },
  {
    id: 'ormarr',
    name: 'Ormarr',
    role: 'Đỡ đòn',
    image: require('../../../assets/anh_mau2/heroes/ormarr.webp'),
  },
  {
    id: 'butterfly',
    name: 'Butterfly',
    role: 'Sát thủ',
    image: require('../../../assets/anh_mau2/heroes/butterfly.webp'),
  },
  {
    id: 'violet',
    name: 'Violet',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/violet.webp'),
  },
  {
    id: 'chaugnar',
    name: 'Chaugnar',
    role: 'Trợ thủ',
    image: require('../../../assets/anh_mau2/heroes/chaugnar.webp'),
  },
  {
    id: 'dieu-thuyen',
    name: 'Điêu Thuyền',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/dieu-thuyen.webp'),
  },
  {
    id: 'zephys',
    name: 'Zephys',
    role: 'Sát thủ',
    image: require('../../../assets/anh_mau2/heroes/zephys.webp'),
  },
  {
    id: 'kahlii',
    name: 'Kahlii',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/kahlii.webp'),
  },
  {
    id: 'omega',
    name: 'Omega',
    role: 'Đỡ đòn',
    image: require('../../../assets/anh_mau2/heroes/omega.webp'),
  },
  {
    id: 'trieu-van',
    name: 'Triệu Vân',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/trieu-van.webp'),
  },
  {
    id: 'mganga',
    name: 'Mganga',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/mganga.webp'),
  },
  {
    id: 'krixi',
    name: 'Krixi',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/krixi.webp'),
  },
  {
    id: 'mina',
    name: 'Mina',
    role: 'Đỡ đòn',
    image: require('../../../assets/anh_mau2/heroes/mina.webp'),
  },
  {
    id: 'lu-bo',
    name: 'Lữ Bố',
    role: 'Đấu sĩ',
    image: require('../../../assets/anh_mau2/heroes/lu-bo.webp'),
  },
  {
    id: 'veera',
    name: 'Veera',
    role: 'Pháp sư',
    image: require('../../../assets/anh_mau2/heroes/veera.webp'),
  },
  {
    id: 'thane',
    name: 'Thane',
    role: 'Đỡ đòn',
    image: require('../../../assets/anh_mau2/heroes/thane.webp'),
  },
  {
    id: 'valhein',
    name: 'Valhein',
    role: 'Xạ thủ',
    image: require('../../../assets/anh_mau2/heroes/valhein.webp'),
  },
];
