import { StyleSheet } from 'react-native';

import { appColors, appRadii, appSpacing } from '@/shared/ui';

import { profileEditUi } from '../../ui/profile-edit-ui';

export const profileEditExperienceStyles = StyleSheet.create({
  avatarEditor: { alignItems: 'center', gap: appSpacing.md, width: 106 },
  avatarInner: {
    alignItems: 'center',
    backgroundColor: profileEditUi.colors.selectedSurface,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarRing: { alignItems: 'center', justifyContent: 'center' },
  category: {
    minHeight: profileEditUi.category.minHeight,
    width: '48.7%',
  },
  categoryContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: appSpacing.md,
    minHeight: profileEditUi.category.minHeight - appSpacing['5xl'],
  },
  categoryCopy: { flex: 1, gap: appSpacing.xxs, minWidth: 0 },
  categoryDirtyDot: {
    backgroundColor: appColors.accent.pink,
    borderRadius: appRadii.pill,
    height: 6,
    width: 6,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: profileEditUi.category.gap,
  },
  categoryIcon: {
    alignItems: 'center',
    backgroundColor: profileEditUi.colors.selectedSurface,
    borderRadius: appRadii.md,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  categoryTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: appSpacing.sm,
  },
  centerText: { maxWidth: 300, textAlign: 'center' },
  coverAction: {
    alignItems: 'center',
    backgroundColor: profileEditUi.colors.backdrop,
    borderRadius: appRadii.pill,
    height: 34,
    justifyContent: 'center',
    position: 'absolute',
    right: appSpacing.md,
    top: appSpacing.md,
    width: 34,
  },
  coverCopy: {
    bottom: appSpacing.lg,
    left: appSpacing.lg,
    position: 'absolute',
  },
  coverEditor: {
    aspectRatio: 16 / 9,
    flex: 1,
    minHeight: 128,
  },
  coverEditorContent: {
    flex: 1,
    minHeight: 128,
    padding: 0,
  },
  dirtyDot: {
    backgroundColor: appColors.accent.pink,
    borderRadius: appRadii.pill,
    height: 7,
    width: 7,
  },
  divider: {
    backgroundColor: profileEditUi.colors.divider,
    height: StyleSheet.hairlineWidth,
    marginVertical: appSpacing.xl,
  },
  fieldLabelRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: appSpacing.sm,
    marginTop: appSpacing.lg,
  },
  fill: { bottom: 0, left: 0, position: 'absolute', right: 0, top: 0 },
  fullWidth: { width: '100%' },
  heroCopy: { flex: 1, gap: appSpacing.xxs, minWidth: 0 },
  heroImage: { borderRadius: appRadii.md, height: 46, width: 46 },
  heroList: { gap: appSpacing.md, marginTop: appSpacing.lg },
  heroPickerCard: { marginBottom: appSpacing.sm },
  heroPickerImage: { borderRadius: appRadii.md, height: 44, width: 44 },
  heroPickerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: appSpacing.xl,
    minHeight: 54,
  },
  heroRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: appSpacing.md,
    minHeight: 54,
  },
  heroSheet: { maxHeight: '84%' },
  heroSheetContent: { padding: appSpacing['3xl'] },
  mediaButton: { minWidth: 100 },
  mediaRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: appSpacing.xl,
  },
  modalBackdrop: {
    backgroundColor: profileEditUi.colors.backdrop,
    flex: 1,
    justifyContent: 'flex-end',
  },
  optionWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: appSpacing.sm,
    marginBottom: appSpacing.md,
  },
  panelContent: { gap: appSpacing.md },
  panelHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: appSpacing.lg,
    marginBottom: appSpacing.sm,
  },
  panelIcon: {
    alignItems: 'center',
    backgroundColor: profileEditUi.colors.selectedSurface,
    borderRadius: appRadii.md,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  panelTitleBlock: { flex: 1, gap: appSpacing.xs },
  playStyleEditorGroup: {
    gap: appSpacing.sm,
    paddingTop: appSpacing.md,
  },
  preview: {
    aspectRatio: profileEditUi.preview.coverAspectRatio,
    borderRadius: profileEditUi.preview.radius,
    overflow: 'hidden',
    position: 'relative',
  },
  previewContent: {
    alignItems: 'center',
    bottom: appSpacing['3xl'],
    flexDirection: 'row',
    gap: appSpacing.xl,
    left: appSpacing['3xl'],
    position: 'absolute',
    right: appSpacing['3xl'],
  },
  previewCopy: { flex: 1, gap: appSpacing.xs, minWidth: 0 },
  saveDockButton: { minWidth: 126 },
  saveDockContent: { width: '100%' },
  saveDockCopy: { flex: 1, gap: appSpacing.xxs, minWidth: 0 },
  sheetCopy: { flex: 1, gap: appSpacing.xs },
  sheetHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: appSpacing.xl,
    marginBottom: appSpacing.xl,
  },
  stateCard: {
    alignItems: 'center',
    gap: appSpacing.xl,
    justifyContent: 'center',
    minHeight: 260,
  },
  subsection: { gap: appSpacing.sm },
});
