-- Seed the reference hero catalog used by profile edit.
--
-- Mobile clients may read public.heroes, but must not create reference rows.
-- Keep the catalog server-owned and idempotently sync it from the app's local
-- hero catalog so profile_heroes can reference stable backend UUIDs.

with hero_catalog(slug, name, role_slug) as (
  values
  ('flowborn', 'Flowborn', 'marksman'),
  ('flowborn_phep', 'Flowborn Phép', 'mage'),
  ('dyadia', 'Dyadia', 'support'),
  ('edras', 'Edras', 'fighter'),
  ('goverra', 'Goverra', 'mage'),
  ('heino', 'Heino', 'mage'),
  ('billow', 'Billow', 'assassin'),
  ('bolt_baron', 'Bolt Baron', 'fighter'),
  ('biron', 'Biron', 'fighter'),
  ('dolia', 'Dolia', 'support'),
  ('charlotte', 'Charlotte', 'fighter'),
  ('tachi', 'Tachi', 'fighter'),
  ('dirak', 'Dirak', 'mage'),
  ('qi', 'Qi', 'fighter'),
  ('erin', 'Erin', 'marksman'),
  ('ming', 'Ming', 'support'),
  ('bijan', 'Bijan', 'fighter'),
  ('bonnie', 'Bonnie', 'mage'),
  ('teeri', 'Teeri', 'marksman'),
  ('yue', 'Yue', 'mage'),
  ('yan', 'Yan', 'fighter'),
  ('aya', 'Aya', 'support'),
  ('aoi', 'Aoi', 'assassin'),
  ('iggy', 'Iggy', 'mage'),
  ('bright', 'Bright', 'marksman'),
  ('lorion', 'Lorion', 'mage'),
  ('dextra', 'Dextra', 'fighter'),
  ('sinestrea', 'Sinestrea', 'assassin'),
  ('thorne', 'Thorne', 'marksman'),
  ('allain', 'Allain', 'fighter'),
  ('zata', 'Zata', 'mage'),
  ('rouie', 'Rouie', 'support'),
  ('laville', 'Laville', 'marksman'),
  ('paine', 'Paine', 'assassin'),
  ('ata', 'Ata', 'tank'),
  ('keera', 'Keera', 'assassin'),
  ('ishar', 'Ishar', 'mage'),
  ('elandorr', 'Eland’orr', 'marksman'),
  ('krizzix', 'Krizzix', 'support'),
  ('volkath', 'Volkath', 'fighter'),
  ('celica', 'Celica', 'marksman'),
  ('zip', 'Zip', 'support'),
  ('enzo', 'Enzo', 'assassin'),
  ('yena', 'Yena', 'fighter'),
  ('errol', 'Errol', 'fighter'),
  ('capheny', 'Capheny', 'marksman'),
  ('hayate', 'Hayate', 'marksman'),
  ('darcy', 'D’Arcy', 'mage'),
  ('veres', 'Veres', 'fighter'),
  ('florentino', 'Florentino', 'fighter'),
  ('sephera', 'Sephera', 'mage'),
  ('quillen', 'Quillen', 'assassin'),
  ('wiro', 'Wiro', 'tank'),
  ('richter', 'Richter', 'fighter'),
  ('elsu', 'Elsu', 'marksman'),
  ('ybneth', 'Y’bneth', 'tank'),
  ('amily', 'Amily', 'fighter'),
  ('annette', 'Annette', 'support'),
  ('baldum', 'Baldum', 'tank'),
  ('roxie', 'Roxie', 'tank'),
  ('marja', 'Marja', 'mage'),
  ('rourke', 'Rourke', 'marksman'),
  ('arum', 'Arum', 'tank'),
  ('wisp', 'Wisp', 'marksman'),
  ('the_flash', 'The Flash', 'mage'),
  ('max', 'Max', 'fighter'),
  ('liliana', 'Liliana', 'mage'),
  ('tulen', 'Tulen', 'mage'),
  ('omen', 'Omen', 'fighter'),
  ('lindis', 'Lindis', 'marksman'),
  ('teemee', 'TeeMee', 'support'),
  ('moren', 'Moren', 'marksman'),
  ('kilgroth', 'Kil’Groth', 'fighter'),
  ('xeniel', 'Xeniel', 'tank'),
  ('wonder_woman', 'Wonder Woman', 'fighter'),
  ('superman', 'Superman', 'fighter'),
  ('telannas', 'Tel’Annas', 'marksman'),
  ('astrid', 'Astrid', 'fighter'),
  ('ryoma', 'Ryoma', 'fighter'),
  ('stuart', 'Stuart', 'marksman'),
  ('arduin', 'Arduin', 'tank'),
  ('zill', 'Zill', 'assassin'),
  ('murad', 'Murad', 'assassin'),
  ('ignis', 'Ignis', 'mage'),
  ('zuka', 'Zuka', 'fighter'),
  ('airi', 'Airi', 'fighter'),
  ('kaine', 'Kaine', 'assassin'),
  ('lauriel', 'Lauriel', 'mage'),
  ('raz', 'Raz', 'mage'),
  ('skud', 'Skud', 'fighter'),
  ('preyta', 'Preyta', 'mage'),
  ('ilumia', 'Ilumia', 'mage'),
  ('slimz', 'Slimz', 'marksman'),
  ('arthur', 'Arthur', 'fighter'),
  ('kriknak', 'Kriknak', 'assassin'),
  ('ngo_khong', 'Ngộ Không', 'assassin'),
  ('maloch', 'Maloch', 'fighter'),
  ('helen', 'Helen', 'support'),
  ('jinna', 'Jinna', 'mage'),
  ('cresht', 'Cresht', 'tank'),
  ('natalya', 'Natalya', 'mage'),
  ('lumburr', 'Lumburr', 'tank'),
  ('fennik', 'Fennik', 'marksman'),
  ('aleister', 'Aleister', 'mage'),
  ('grakk', 'Grakk', 'tank'),
  ('nakroth', 'Nakroth', 'assassin'),
  ('taara', 'Taara', 'tank'),
  ('toro', 'Toro', 'tank'),
  ('yorn', 'Yorn', 'marksman'),
  ('gildur', 'Gildur', 'tank'),
  ('alice', 'Alice', 'support'),
  ('azzenka', 'Azzen’Ka', 'mage'),
  ('ormarr', 'Ormarr', 'tank'),
  ('butterfly', 'Butterfly', 'assassin'),
  ('violet', 'Violet', 'marksman'),
  ('chaugnar', 'Chaugnar', 'support'),
  ('dieu_thuyen', 'Điêu Thuyền', 'mage'),
  ('zephys', 'Zephys', 'assassin'),
  ('kahlii', 'Kahlii', 'mage'),
  ('omega', 'Omega', 'tank'),
  ('trieu_van', 'Triệu Vân', 'fighter'),
  ('mganga', 'Mganga', 'mage'),
  ('krixi', 'Krixi', 'mage'),
  ('mina', 'Mina', 'tank'),
  ('lu_bo', 'Lữ Bố', 'fighter'),
  ('veera', 'Veera', 'mage'),
  ('thane', 'Thane', 'tank'),
  ('valhein', 'Valhein', 'marksman')
)
insert into public.heroes (slug, name, role_id)
select
  hero_catalog.slug,
  hero_catalog.name,
  roles.id
from hero_catalog
left join public.roles on roles.slug = hero_catalog.role_slug
on conflict (slug) do update
  set name = excluded.name,
      role_id = excluded.role_id;
